dpkp/kafka-python

kafka/protocol.py
The patch applied in the PR #268 only allowed for uncompressed messages to be assigned a key. The key was ignored when using CODEC_GZIP or CODEC_SNAPPY.
=> Added keys to compressed messages (both gzip and snappy).

kafka/producer/simple.py, test/test_producer_integration.py
random_start=False is dangerous. Any client that initializes a
SimpleProducer and performs only a single publish batch will always go
to partition 0. A common use-case for this is command line utilities,
or web-servers which are unable to cache the SimpleProducer instance
between calls. This would result in partition 0 becoming overloaded, and all other partitions getting starved.
=> Randomize start by default for SimpleProducer

kafka/__init__.py
Hey, just noticed that the new ``KafkaConsumer``is not in ``__all__`` making it hard to import. This PR fixes it :)
=> KafkaConsumer should be in __all__.

kafka/common.py, test/test_client.py
I was searching through modifications between 0.9.0 and 0.9.1 in order to upgrade our deployed software and came across the same bug that @dpkp discovered with the check_error() method:
https://github.com/mumrah/kafka-python/commit/0d57c2718fcf3819f2c18911126f245e9e9ce3e0#diff-9e97caff580d80c9a0eb85fe22ffb3d1R184
However the fix involved creating a NoError exception which seems a bit akward. Here's a alternative version.
Cheers,
Alex
=> Use reflection to avoid multiple errno definitions

kafka/util.py
circle reference between SimpleConsumer and ReentrantTimer .
=> fix circle reference

kafka/producer/simple.py, test/test_producer.py
Prevents people from doing the following:
```
from kafka import KafkaClient, SimpleProducer
kafka = KafkaClient(hosts=["localhost:9092"])
producer = SimpleProducer(kafka)
producer.send_messages("test", b"some message")
```
Which would give this error:
```
Traceback (most recent call last):                                                                                
File "test_kafka.py", line 7, in <module>                                                                       
producer.send_messages("test", b"some message")                                                               
File "/home/sontek/venvs/notebooks3/src/kafka-python/kafka/producer/simple.py", line 71, in send_messages       
partition = self._next_partition(topic) …
```
=> Alert if the topic is not sent as bytes

kafka/util.py
threading.Event.wait return values are different for python2.6
https://docs.python.org/2/library/threading.html#threading.Event.wait
this causes the current reentrant timer to never stop when using python2.6
=> Fix python2.6 threading.Event bug in ReentrantTimer

kafka/client.py
should fix the travis-ci build failures, caused by new behavior in pypy 2.5.0
list({1: 'foo', 0: 'bar'})
pypy: [1, 0]
py27: [0, 1]
which was causing chaos with the tests
=> Always return sorted partition ids in client.get_partition_ids_for_topic()

README.rst, setup.py
This allows us to have our README show up on pypi.  https://pypi.python.org/pypi/kafka-python doesn't look as nice as it will with this change :)
=> Switch to rst and use in setup.py

kafka/partitioner/base.py, kafka/partitioner/hashed.py, kafka/partitioner/roundrobin.py, kafka/producer/keyed.py, test/test_failover_integration.py, test/test_producer_integration.py
this is a test for issue #313 -- first step to fixing!
=> Handle keyed producer failover

kafka/producer/base.py, kafka/util.py
Consumer, Producer and ReentrantTimer all create daemonized threads. Problem: when destroying these objects, the daemonized threads are not destroyed and the threads live forever with no mean to reach them.
This created issue #323, which I could deal with by using stop() manually, but there is no reason to force the user to force the user to do that when it could be dealt with automatically.
This pull request fixes this.
=> Properly destroying the objects that contain daemonized threads

kafka/client.py, kafka/consumer/kafka.py
A few small cleanups to KafkaClient:
- accept client_id and group_id as string or bytes
- avoid topic_partition KeyError
- return empty list from get_partition_ids_for_topic for unknown topics
to make the return type consistent (always a list)
=> Kafka client edits

kafka/conn.py, kafka/producer/base.py, test/test_conn.py
I decided to finish work of @snaury by fixing the conflicts and compatibility issues, and preparing the other PR for same theme. This PR is directly related with #151 and #153.
=> Threading for async batching

kafka/consumer/multiprocess.py
I could be wrong, but it seems that there's wrong partitions distribution logic for `MultiProcessConsumer`.
It's not even at all currently, it can be checked with the following function (cut from the code and wrapped):
```python 
>>> def get_chunks(partitions, num_procs, partitions_per_proc=0):
...     if not partitions_per_proc:
...             partitions_per_proc = round(len(partitions) * 1.0 / num_procs)
...             if partitions_per_proc < num_procs * 0.5:
...                     partitions_per_proc += 1
...     chunker = lambda *x: [] + list(x)
...     return map(chunker, *[iter(partitions)] * int(partitions_per_proc))
...
```
Wrong cases examples:
```python
>>> get_chunks(range(16), 3)
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, None, None, None, None]]
>>> …
```
=> Wrong partitions distribution logic for MP Consumer

kafka/producer/base.py, kafka/protocol.py, test/test_producer_integration.py, test/test_protocol.py
There're some possible changes relative to #325.
As create_message_set() method is called only from base Producer class and from _send_upstream(), I've changed it a little bit, so messages sent as a list of (msg, key) tuples. I've added some basic tests also.
Take a look please, probably it can be improved.
(This PR is squashed to the other branch #326.)
=> Correct message keys for async batching mode

kafka/codec.py
=> Use context managers in gzip_encode / gzip_decode

kafka/common.py
Another small cleanup -- via vshlapakov PR 331
=> Fixup indentation in kafka/common.py; add links to protocol definitions

kafka/consumer/simple.py
This change enables an explicit call to
commit() to actually commit the offsets even if auto_commit is False. Currently a consumer is not
able to commit the offsets after a seek until at least one message is read.
=> Enable commit on seek

kafka/consumer/kafka.py
deprecated upstream: http://kafka.apache.org/documentation.html#highlevelconsumerapi
metadata_broker_list was such a confusing name
=> Deprecate metadata_broker_list in favor of bootstrap_servers

docs/requirements.txt, docs/usage.rst, kafka/consumer/kafka.py, test/test_consumer_integration.py
More docstrings and move examples to Usage section of sphinx docs.
=> KafkaConsumer documentation

kafka/consumer/base.py
consumer.stop() is used to cleanup threads / processes.  This change is intended to cleanup multiprocess consumers which previously seem to have been just garbage collected.  It will also cause the autocommit batch timer to commit on delete.
=> Stop consumers on delete

kafka/client.py, test/test_client.py
Rollover KafkaClient correlation ids at 2**31 to keep within int32 protocol encoding
Fixes Issue #344
=> correlation_id modulo

kafka/consumer/base.py, kafka/consumer/multiprocess.py, kafka/consumer/simple.py, test/test_consumer_integration.py, test/test_failover_integration.py
Fix for Issue #173 (and #347) w/ included test case from @alisaifee
=> fetch commit offsets in base consumer unless group is None

kafka/client.py, kafka/consumer/base.py, kafka/consumer/multiprocess.py, kafka/producer/base.py, kafka/producer/keyed.py, test/test_client.py, test/test_client_integration.py, test/test_consumer_integration.py, test/test_failover_integration.py, test/test_producer_integration.py, test/testutil.py
I noticed that python3 string topics were supported in SimpleProducer.send_messages but not elsewhere in the API. This change makes python3 string topics supported throughout the public API.
This required changes in some testing code to ensure that bytes were used when building internal structs for return and sending to kafka service.
=> Make external API consistently support python3 strings for topic.

kafka/consumer/base.py, kafka/producer/base.py
=> Register atexit handlers for consumer and producer thread/multiprocess cleanup

kafka/consumer/kafka.py
Fix a str/bytes bug set_topic_partitions when using { (topic,...... partition): offset, } interface
Some small cleanups in fetch_messages to topic/partition handling
=> KafkaConsumer topic/partition fixes

kafka/client.py
Return a list of responses and include individual (unraised) FailedPayloadsError instances rather
than always raising a FailedPayloadsError. This should allow producers to determine which payloads succeeded and which failed, specifically.
=> Refactor client request/response handling to support better retries

kafka/client.py
=> Clear local metadata cache before refresh in client.load_metadata_for_topics()

kafka/consumer/kafka.py
Previously you would see this error:
```
self.offsets._fetch[(topic, partition)],
AttributeError: 'function' object has no attribute '_fetch'
```
=> Fix calling of _offsets

kafka/common.py, kafka/consumer/simple.py, test/test_failover_integration.py
about #386. It‘s a not that elegant fix, but works...
=> try to fix uncaught FailedPayloadsError in consumer

docs/usage.rst, kafka/producer/keyed.py, test/test_producer_integration.py
Keep the producer interfaces consistent
=> Deprecate KeyedProducer.send in favor of send_messages

kafka/consumer/multiprocess.py, test/test_consumer.py
=> Support optional partitions kwarg in MultiProcessConsumer

kafka/consumer/kafka.py
See #364 -- this revision should prevent KeyError exceptions so that operation is a bit smoother.
It is still unknown, however, how/why an unrecognized topic-partition gets sent to task_done during normal message processing.
=> KafkaConsumer.task_done: warn and skip unrecognized topic-partitions

kafka/consumer/kafka.py
Update KafkaConsumer to utilize new per-request FailedPayloads interface. Previously, because the consumer code could not determine which request had caused the FailedPayloadsError it had to fail the entire batch of requests. Now we can just skip the failed request and process other responses that may have succeeded.
=> Kafka consumer failed payloads

kafka/client.py, test/test_client_integration.py
Fix a bug in KafkaClient broker-aware request processing that caused responses to not be correlated with correctly before returning.
=> Client request response ordering

kafka/consumer/base.py, kafka/consumer/simple.py, test/test_consumer.py
fix #371 (commit() exceptions) and related issue in reset_partition_offset
=> Consumer more exception handling

.travis.yml, README.rst, build_integration.sh, docs/index.rst, servers/0.8.2.1/resources/kafka.properties, servers/0.8.2.1/resources/log4j.properties, servers/0.8.2.1/resources/zookeeper.properties, test/test_client_integration.py, test/test_consumer_integration.py
This updates test configuration to use 0.8.2.1 instead of 0.8.2.0 for integration tests.
=> Test kafka 0.8.2.1

kafka/consumer/simple.py
- attempt to make these easier to read
- add marginal retry logic to internal _fetch loop
=> Refactor SimpleConsumer get_messages and _fetch

kafka/partitioner/__init__.py, kafka/partitioner/hashed.py
=> Use MurmurHash2 for key partition hashing

kafka/client.py, kafka/consumer/base.py
These two log prints are very noisy when we deal with high volume topics and large clusters, and in my opinion not particularly useful from a client perspective unless in debug level.
The replica not available log, indeed, is not specific of the topic/partition of the particular consumer/producer. In a Kafka cluster with a lots of topics this ends up flooding the logs with warning about under replicated topics which the user most of the times is not interested in. This is a very important information for the cluster administrator, but the latter should rely on metrics and logging provided by Kafka itself instead of a client library.
=> Lower logging level on replica not available and commit

kafka/client.py
The caller is expecting failure responses, not thrown exceptions; make sure to catch exceptions from calls that might provoke a metadata request.
This avoids send_produce_request unexpectedly throwing an exception, which ends up killing the async producer thread.
Fixes issue #429
=> Catch KafkaUnavailableError in _send_broker_aware_request

kafka/producer/base.py, test/test_producer.py, test/test_producer_integration.py
PR for #408.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/mumrah/kafka-python/409)
=> Allow null payload for deletion feature

kafka/consumer/base.py, kafka/consumer/multiprocess.py, kafka/consumer/simple.py
Can someone please check this PR? I saw a travis fail in one of the builds. However, according to traceback it does not have relation with it.
=> allow to retrieve partition info in mp consumer

kafka/producer/base.py, test/test_producer.py
Reworked the if statement logic to only call stop() on not-stopped objects.
Fixing #434 
added tests
Ironically, this was one of the only pieces of code not "covered" by unit tests.
=> Reworked the if statement logic to only call stop() on not-stopped producer objects

kafka/partitioner/hashed.py, test/test_partitioner.py
Murmur2Partitioner currently doesn't run on Python 3, or when it
is passed a bytearray, and it differs from the Kafka Java implementation in its
handling of leftover bytes (the Java switch statement falls through between
cases).  
This PR:
Avoid further type changes when Murmur2Partitioner is passed a byte
array.  Change leftover-bytes logic to match the Java switch statement,
and add tests to verify that partition selection matches Java implementation.
=> Fix translation of Java murmur2 code, fix byte encoding for Python 3.

MANIFEST.in
Allows downstream OS packagers and porters to include the LICENSE file in package installations
=> Include LICENSE in PyPI sdist

kafka/codec.py, kafka/producer/base.py, kafka/protocol.py
The default compression level for gzip is 9 (highest) in Python.
For a lot of use cases a lower compression level like 6 will provide good (enough) compression and is significantly faster.
=> allow to specify compression level for codecs which support this

kafka/consumer/kafka.py
Allows users to define subclasses of KafkaConsumer with different default configs.
=> Set default config on consumer class to support subclass config changes.

kafka/consumer/multiprocess.py, kafka/consumer/simple.py, test/test_consumer_integration.py
Modified MultiProcessConsumer's and SimpleConsumer's `block` argument to
allow integer value which defines the number of messages to block for.
This allows callers to ask for a high number of messages and block only
until some of them are received.  Otherwise callers would have to request
messages one by one or block for some time.
=> Consumers get_messages: allow blocking until some messages are received

kafka/client.py, kafka/producer/base.py
If an uncaught exception occurs in _send_messages() the thread sending
data to Kafka (asynchronously) will crash and the queue will never be
emptied. To reproduce:
1) Run an Async producer.
2) Kill the Kafka server.
3) Restart the Kafka server.
The communication thread dies shortly after step 2. After step 3 the
communication does not resume without this commit.
The changes in both files prevent an Exception from being thrown through
to do main communication process, which could cause the crash.
=> Prevents crashing communication thread of async producer

kafka/client.py, kafka/conn.py, test/test_conn.py
Send broker aware requests in parallel and use select to read from available sockets. 
This is a good improvement when using large clusters and reading from multiple partitions/topics which span on many brokers. 
Do not expect performance improvement when reading from a single partition.
=> Use unblocking io for broker aware requests

kafka/client.py, kafka/common.py, kafka/protocol.py, test/test_protocol.py
I've added basic support for the consumer coordinator in the Kafka broker, specifically for fetching offsets from the brokers that have been committed to Kafka, as opposed to Zookeeper. Internally, we use this library for some API and monitoring work, and one of the functions we need is to retrieve offsets that have been committed using kafka storage.
I've added a client request method for sending consumer metadata requests, along with the appropriate encoder and decoder routines. I have also added a _send_consumer_aware_request method which uses the consumer metadata information to find the coordinator for the specified consumer group and send requests to that broker. These parts are the basic support framework for communicating with the consumer coordinator.
In addition, to support …
=> Initial support for consumer coordinator

kafka/consumer/kafka.py, kafka/consumer/simple.py, test/fixtures.py
tested locally with `pylint --rcfile=pylint.rc -E kafka test`. should
pass travis builds.
=> new pylint disables for pylint 1.5.1

kafka/client.py, kafka/producer/base.py, test/test_producer_integration.py
=> Producer.stop() should block until async thread completes

kafka/consumer/kafka.py
In case the answer to #425 is "you can't", this adds a `close` method to KafkaConsumer. I didn't add tests because I didn't see any for KafkaClient.
Fixes #425
=> Add KafkaConsumer#close

kafka/client_async.py, kafka/cluster.py, kafka/consumer/group.py, test/test_client_async.py
Because timeouts were not considered, calls to poll() with long timeouts and no pending requests could result in large delays for heartbeat / autocommit tasks.
=> Add delayed task timeouts to _poll calls

README.rst, docs/index.rst, docs/install.rst, kafka/codec.py, test/test_producer.py, tox.ini
Kafka brokers attempt to implement the LZ4 framing specification, but inadvertently included the magic bytes in the header checksum calculation. To support kafka's LZ4 compression, we have to compress / decompress as normal but overwrite the checksum w/ a broken [when compressing] or correct [when decompressing] byte.
=> Handle broken LZ4 framing 

kafka/client_async.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/util.py, test/test_coordinator.py
closes #552
saw these errors after running consumers for a while (hrs or sometimes days):
```
sync-files-cache_1 |   File "/usr/local/lib/python2.7/dist-packages/kafka/consumer/group.py", line 182, in __init__
sync-files-cache_1 |     self.config['api_version'] = self._client.check_version()
sync-files-cache_1 |   File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 615, in check_version
sync-files-cache_1 |     self.poll(future=f)
sync-files-cache_1 |   File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 355, in poll
sync-files-cache_1 |     responses.extend(self._poll(timeout, sleep=sleep))
sync-files-cache_1 |   File "/usr/local/lib/python2.7/dist-packages/kafka/client_async.py", line 390, in _poll
sync-files-cache_1 |     ready, _, _ = …
```
=> break up some circular references and close client wake pipe on __del__

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py
This should fix performance regression noted in #551 .
=> Dont override system rcvbuf or sndbuf unless user configures explicitly

kafka/consumer/group.py
After manually assigning a TopicPartition and seeking it to the end, I didn't find
any way to obtain the offset. The reason was this bug in the position method. Now
the position method correctly refreshed the position after seek_to_end() is called.
=> Bug fix: KafkaConsumer.position()

kafka/producer/base.py
Our app uses `SimpleProducer` and logs lots of these warnings (from line 438):
producer.stop() called, but producer is not async
This destructor appears to be the cause.
(Also, is it wise to do a thread join from a destructor?)
=> Silence suprious warnings

kafka/consumer/group.py, kafka/coordinator/base.py, test/test_consumer_group.py, test/test_coordinator.py
Fix heartbeat 2 bugs identified in #571 (may also fix #569):
- a pending metadata request to the group coordinator during a heartbeat causes the heartbeat to not reschedule propertly
- consumer iteration does not pause to process heartbeat responses, which can cause inadvertent timeouts during slow message processing against large fetch request batches
=> Fix Consumer Heartbeat Bugs

kafka/producer/buffer.py, test/test_producer.py
This PR fixes a critical bug in how internal produce message buffers are handled. All allocated buffers should be 'empty' when returned from the pool. Fixes #576 and #580
=> Truncate deallocated message buffers

kafka/producer/record_accumulator.py
Traceback:
```
kafka-python-producer-2-network-thread Uncaught error in kafka producer I/O thread
File "/home/travis/build/dpkp/kafka-python/kafka/producer/sender.py", line 57, in run
self.run_once()
File "/home/travis/build/dpkp/kafka-python/kafka/producer/sender.py", line 116, in run_once
self.config['request_timeout_ms'], self._metadata)
File "/home/travis/build/dpkp/kafka-python/kafka/producer/record_accumulator.py", line 251, in abort_expired_batches
for tp, dq in six.iteritems(self._batches):
RuntimeError: dictionary changed size during iteration
```
=> Fix producer threading bug that can crash sender

kafka/client_async.py, kafka/coordinator/consumer.py
When least_loaded_node returns None, there really are no brokers available.
=> Improve handling of least_loaded_node failure

kafka/consumer/group.py
=> KafkaConsumer.poll should sleep to prevent tight-loops

kafka/client.py, test/test_client.py
Fixes https://travis-ci.org/zackdever/kafka-python/jobs/116534314.
The problem this is addressing is that SimpleClient.send_produce_request(fail_on_error=False) could still fail with a `LeaderNotAvailableError ` or `UnknownTopicOrPartitionError` because they were not caught in `_payloads_by_broker`.
The problem with this approach is that this will now mask those two errors as the more generic `FailedPayloadsError` to all callers of `_send_broker_aware_request`, not just `send_produce_request`.
It's a non-trivial change to isolate this change just to `send_produce_request`, and because this will soon be deprecated, I think this is a decent approach. This will prevent hard failures during produce that are not expected, and at worst may require users to add `FailedPayloadsError` to the list …
=> Catch all errors thrown by _get_leader_for_partition in SimpleClient

kafka/client.py, kafka/client_async.py, kafka/conn.py, test/test_client.py, test/test_client_async.py, test/test_conn.py
IPv6 address without port can be defined as the IPv6 address.  If the address
is a hostname or if a port is included, then the address MUST be wrapped
in brackets [] (E.g. [somehost]:1234 or [fd00:1001::2]:1234).
Fixes  #616
Tests included.
=> Kafka IPv6 Support.

kafka/client_async.py, kafka/conn.py, kafka/consumer/fetcher.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/producer/sender.py, kafka/protocol/admin.py, kafka/protocol/commit.py, kafka/protocol/fetch.py, kafka/protocol/group.py, kafka/protocol/legacy.py, kafka/protocol/metadata.py, kafka/protocol/offset.py, kafka/protocol/produce.py, test/test_client.py, test/test_client_async.py, test/test_conn.py, test/test_consumer_group.py, test/test_coordinator.py, test/test_fetcher.py
This change is intended to simplify adding support for multiple api versions
=> Use version-indexed lists for request/response protocol structs

kafka/consumer/fetcher.py
Related to #631 
Add debug logging when skipping messages internally due to offset checks
Increase coverage of StopIteration checks when unpacking message sets
Dont re-send a FetchRequest that is pending in Fetcher._records
=> Small improvements to fetching logic

kafka/client_async.py, kafka/conn.py, test/test_client_async.py
Also pushes check_version() code from KafkaClient to BrokerConnection.
This work is cleanup in preparation for a transition from select to selectors
=> Use KafkaClient callback to manage BrokerConnection state changes

.gitignore, kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py, servers/0.10.0.0/resources/kafka.properties, servers/0.9.0.0/resources/kafka.properties, servers/0.9.0.1/resources/kafka.properties, test/conftest.py, test/fixtures.py
Adapt #474 to work with new KafkaClient / KafkaConsumer / KafkaProducer. closes #253
=> Support SSL connections

kafka/consumer/fetcher.py
Still need to investigate why tests aren't failing.
Could also look at possibly removing `fetch_throttle_time_sensor` entirely when the api version is 0. This isn't what caused the bug, but I just realized that `throttle_time_ms` is only available starting with api version 1.
=> Fix throttle_time_ms sensor for FetchRequest v0

kafka/future.py, test/__init__.py, test/test_coordinator.py
Error handling in call/errbacks was different depending on whether the future had already completed. Exceptions were not caught if a callback was added after the future had completed, but they were caught if they were added before the future had completed. This PR ensures that they are always caught.
Additionally, because errors are logged, but not thrown in future callbacks, our tests were not failing on errors such as #667. This PR adds a class variable `error_on_callbacks` to `Future` that can be set so that errors bubble up. By default this is off, but is always turned on for testing. Users could also use this flag if useful.
=> Consistent error handling in future call/errbacks + better test failures

kafka/client_async.py, kafka/conn.py, test/test_conn.py
Follow-up to EasyPost's PR #666 / Issue #661 . Sockets disconnected abruptly were being left to time out. This PR should detect failure on recv() and fail pending requests immediately / trigger metadata update.
=> Improve socket disconnect handling

kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py, kafka/protocol/admin.py
Use the api to identify 0.10 brokers in check_version.
Leaving deeper support for ApiVersion response (min / max versions) for a separate task.
=> Add protocol support for ApiVersionRequest

kafka/consumer/simple.py, kafka/protocol/legacy.py, test/test_consumer_integration.py
Summary:
Fix legacy SimpleConsumer with compressed messages. Decompress messages if they are compressed and add a test for the new logic.
Test Plan:
KAFKA_VERSION=0.9.0.1 tox -e py27 test/test_consumer_integration.py
=> [SimpleConsumer] Fix legacy SimpleConsumer with compressed messages

kafka/conn.py
When the address family is not provided, `self.host` is resolved to one
of the IP addresses and replaced by it. The SSL context is then built
using `self.host` which is now an IP instead of the proper name. Most of
the time, hostname cannot be checked this way. Therefore, save the
original hostname in a dedicated property and use this property for the
SSL context.
Only lightly tested with `example.py`.
=> kafka/conn: use original hostname for SSL checks

kafka/conn.py
If you attempt to instantiate a KafkaConsumer object like this:
k = KafkaConsumer('ILikeTopics', bootstrap_servers = ["myserver:9092"])
.. and the Kafka instance on "myserver" happens to believe that its name is something like "ip-10-0.0.1.ec2.internal", which you can't resolve, you'll get a trace that looks like:
File "my_kafka_test.py", line 2, in <module>
k = KafkaConsumer('ILikeTopics', bootstrap_servers = ["myserver:9092"])
File "/Users/erik/virtualenvs/my_kafka_test/lib/python2.7/site-packages/kafka/consumer/group.py", line 227, in __init__
self.config['api_version'] = self._client.check_version()
File "/Users/erik/virtualenvs/my_kafka_test/lib/python2.7/site-packages/kafka/client_async.py", line 673, in check_version
self._maybe_connect(node_id) …
=> supplement socket.gaierror exception in BrokerConnection.connect()

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py
A user can provide a CRL whose peer certificate will be checked
against. This only works with Python 3.4+ and Python 2.7.9+.
Lightly tested with `example.py`.
=> Add CRL support to SSL support

kafka/consumer/fetcher.py, kafka/errors.py, kafka/producer/kafka.py, kafka/producer/sender.py, kafka/protocol/fetch.py, kafka/protocol/produce.py, test/test_fetcher.py, test/test_sender.py
Kafka 0.10 introduces new api versions that use the new message format v1, which adds record timestamps and relative offsets. See KIP-31 / KIP-32.
=> Use Fetch/Produce API v2 for brokers >= 0.10

kafka/codec.py, kafka/errors.py, kafka/producer/buffer.py, kafka/protocol/message.py, test/test_codec.py
see KAFKA-3160
Also note that the python wrapper for lz4 currently used by kafka-python (lz4tools) does not return sufficient data from decompressFrame to support incremental decompression. If the first decompress attempt is partial, raise RuntimeError. In practice this means that decompressed lz4 message sets must be <= 4MB. This is larger than the max message size setting for default kafka broker configuration, so it should not affect most users.
=> Use standard LZ4 framing for v1 messages / kafka 0.10

kafka/client_async.py, test/test_client_async.py
Fix #689 
(1) Bootstrap connections that result in useable cluster metadata were being discarded without closing the socket.
(2) "wake" sockets were only closed in KafkaClient.__del__ which was not called during normal gc due to reference cycle.
=> Fix socket leaks in KafkaClient

kafka/producer/future.py, kafka/producer/record_accumulator.py
Fix #677 
Changes FutureProduceResult `await()` to `wait()`
=> Dont use soon-to-be-reserved keyword await as function name

kafka/producer/kafka.py, kafka/producer/record_accumulator.py, kafka/producer/sender.py
Fix #595 -- when max.in.flight.request.per.connection = 1, attempt to guarantee ordering in producer
=> KAFKA-3197: improve producer batch ordering

kafka/producer/kafka.py, kafka/util.py, test/test_producer.py
=> Use weakref when registering a producer.close atexit to fix normal gc

kafka/client_async.py, kafka/cluster.py, test/test_client_async.py
If the cluster enters complete failure -- no nodes are available to service a metadata request -- the client was prone to busy polling, which would peg CPU at 100%. This PR aligns backoff behavior with the official java client using the 'retry_backoff_ms' configuration parameter.
=> Avoid busy poll during metadata refresh failure with retry_backoff_ms

kafka/client_async.py, kafka/producer/sender.py
`add_topic` is expected to be idempotent and is called (via `_wait_on_metadata`) on every `producer.send()` . By checking the temporary `_topics_to_add` set, the prior behavior would trigger a very large number of client thread wakeups. This PR alters add_topic so that it checks the client topic list directly, short-circuiting the need to wakeup the client thread. This is a cross-thread check w/o synchronization, but I believe it should be safe in this context.
=> Wakeup socket optimizations

kafka/consumer/fetcher.py
=> Randomize consumer partition processing order to improve balance

kafka/producer/kafka.py
If python gc attempts to cleanup a producer object that hasn't fully initialized it can generate a scary log message. Though note that the gc system ignores this error and continues on unabated. Nonetheless, the log message is messy and causes confusion.
Fix #741
=> Avoid AttributeErrors in _unregister_cleanup

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py
Our team wanted to be able to set an ssl_password in config so a KafkaConsumer could be created with SSL certification and not need to enter a password manually. This minor changes add the ssl_password in all the default config dicts necessary and allow for it to be set when instantiating a consumer instance.
=> Add ssl_password to default_config dicts. Send ssl_password when loading cert chains

kafka/consumer/fetcher.py, kafka/consumer/subscription_state.py
KafkaConsumer iteration was broken for compacted topics. This PR should fix that as well as fix the `seek()` semantics that are affected by it.
@zackdever -- thank you for finding this bug!
=> Fix consumer iteration on compacted topics

kafka/producer/buffer.py, test/test_buffer.py
This addresses producer-side bug from #718 .
=> Fix bug causing KafkaProducer to double-compress message batches

kafka/consumer/fetcher.py, kafka/consumer/group.py
Attempt to simplify unpacking of compressed messages. Related to #718 -- KafkaConsumer no longer attempts to decompress more than a single layer of messages. If a message set was double-compressed by the producer, this patch will cause KafkaConsumer to return the compressed bytes as a single message for the entire batch. A warning will be logged, but otherwise the data will no longer appear "skipped", it will appear as corrupted. If the user wants to simply skip these messages, there is a new configuration parameter `skip_double_compressed_messages`
Longer term we should refactor Message / MessageSets to expose raw bytes and let handle_fetch_response unpack and decompress (this is how the java client operates)
=> Drop recursion in Fetcher _unpack_message_set

kafka/errors.py, kafka/future.py
Fix #759 
- add error type to all KafkaErrors
- add args to BrokerResponseError
- drop description from BrokerResponseError
- fix bug logging errbacks as callbacks
=> Cleanup error logging

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py, test/test_client_async.py, test/test_consumer_group.py, test/test_coordinator.py, test/test_fetcher.py, test/test_sender.py
api_version was previously converted to a tuple internally so that we could easily compare versions. This PR changes the interfaces for KafkaClient.check_version and BrokerConnection.check_version to return these tuples (previously returned str). And the top-level configuration api_version parameter to KafkaConsumer and KafkaProducer also is changed to a tuple.
Also changed is that KafkaClient now performs a check_version probe during `__init__` by default. Previously it did not, although it did perform network IO via bootstrapping. The check_version call does potentially raise an exception, so any user that is using KafkaClient directly would need to either pass an explicit api_version or try / except for NoBrokersAvailable.
The goal here is to simplify api_version handling internally, …
=> check_version / api_version should always be tuples

kafka/client_async.py, kafka/consumer/group.py, kafka/producer/kafka.py
Allows using a selector other than DefaultSelector.
=> Expose selector type as config option

kafka/coordinator/consumer.py, test/test_coordinator.py
=> KAFKA-3117: handle metadata updates during consumer rebalance

kafka/coordinator/consumer.py, test/test_coordinator.py
=> KAFKA-3486: fix autocommit when partitions assigned manually

kafka/consumer/group.py
Couldn't find a `CONTRIBUTING.md` or similar, so I apologize if this doesn't follow guidelines; let me know, and I'll fix it. :)
=> Fix typo in KafkaConsumer documentation

kafka/protocol/pickle.py
Issue: _pickle_method() uses attributes are not python 3 compatible.
Fix: updated to use python 3 special attributes.
=> Change _pickle_method to use python3 special attributes

kafka/consumer/group.py
PR #750 added the code for passing along a password, but not any documentation on it.
=> Document the ssl_password config option

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py
Fixes #717 
This PR enables TCP_DELAY by default to reduce send latency (possibly at the expense of throughput). To allow more general socket tuning, I've also added a configuration parameter `socket_options` which will be passed directly to `setsockopt()` on each broker connection.
=> Improve send latency with TCP_NODELAY

kafka/producer/kafka.py, kafka/producer/record_accumulator.py, kafka/producer/sender.py
Change to make KafkaConsumer and KafkaProducer consistent
=> Rename _DEFAULT_CONFIG -> DEFAULT_CONFIG in KafkaProducer

kafka/consumer/subscription_state.py
see https://issues.apache.org/jira/browse/KAFKA-3960
=> KAFKA-3960: Fix offset fetch when partitions are manually assigned

kafka/cluster.py
Add `ClusterMetadata.with_partitions(topic_partitions)` to mirror java client. This method returns a copy of the cluster metadata with the new partitions added manually.
=> Metadata with_partitions()

kafka/coordinator/base.py, test/test_consumer_group.py
The coordinator updates the local generation_id after JoinGroup, but new assignments are not available until after SyncGroup. Use the coordinator.rejoining flag to wait until all consumers are in new generation and have new assignments.
=> Fix consumer group test bug

.covrc, test/fixtures.py, tox.ini
Attempt to fix transient kafka fixture issues that are seen on travis. The travis logs suggest that kafka brokers are failing because of port conflicts. This PR changes the fixture retry process to try with a new port number after failing.
=> Fixture auto ports

kafka/conn.py
The goal here is to avoid potentially split packets when TCP_NODELAY is set
=> Send combined size and payload bytes to socket

kafka/protocol/message.py
The help string indicates a return value of `0` or `1` but since self.TIMESTAMP_TYPE_MASK=8, the actual return values are `8` or `0`.
=> Fix message timestamp_type

.gitignore, kafka/partitioner/base.py, kafka/partitioner/hashed.py, kafka/partitioner/roundrobin.py, test/test_partitioner.py
The partitioners have been updated to use the new KafkaProducer calls and support the old SimpleProducer APIs.
The partitioners are callable and the RoundRobinPartitioner caches the last partition and supports dynamic partition altering.
=> Partitioners fix

kafka/consumer/fetcher.py, kafka/consumer/group.py, test/test_consumer_group.py, test/test_consumer_integration.py, test/test_fetcher.py
max_poll_records allows limiting the number of records returned by KafkaConsumer.poll(). This may be useful when record processing may take longer than the consumer group session timeout. This change also simplifies the python iterator logic to simply call poll() internally w/ max_poll_records 1.
Fixes #592
=> KAFKA-3007: KafkaConsumer max_poll_records

kafka/partitioner/__init__.py, kafka/partitioner/hashed.py, test/test_partitioner.py
=> Fix murmur2 bug handling python2 bytes that do not ascii encode

kafka/conn.py
In Kafka 9, `advertised.host.name` was renamed to `advertised.listeners`
=> Update param in warning

kafka/client_async.py, kafka/conn.py
Currently we check for request timeouts in BrokerConnection.recv(). But this method is only called in KafkaClient if the socket is polled as read / write ready. If a socket times out without causing a read / write event, the request will never timeout. This happens, for example, if a broker hits a deadlock like https://issues.apache.org/jira/browse/KAFKA-3994
This PR moves the request timeout to the KafkaClient._poll loop and checks every connection on every _poll call.
=> Always check for request timeouts

kafka/coordinator/base.py, kafka/coordinator/consumer.py
The current logging does not show what error causes the group coordinator to be marked dead. This PR passes the upstream error to coodinator_dead() so that it can be logged.
=> Always include an error for logging when the coordinator is marked dead

kafka/client_async.py
``topics`` were set to ``[]`` instead of ``None`` because of empty ``self._topics`` set for MetadataRequest_v1
=> Fix of wrong MetadataRequest in case of empty topics list

kafka/consumer/subscription_state.py
I accidentally tried to `.subscribe([None])` this morning, and it took a little while to figure out what I'd done wrong.
Thought this check might be useful in the future. What do you think?
=> Raise exception if given a bad topic name

kafka/client_async.py, kafka/coordinator/base.py
PR to address a possibly strange state in which we mark the coordinator dead during the request-draining loop in ensure_active_group. If coordinator_id is None, in_flight_request_count() will return the *total* requests across all nodes. To avoid even stranger interactions with state mutation, disable delayed task running while we're trying to drain the in-flight-requests.
=> Fix possible request draining in ensure_active_group

kafka/partitioner/default.py, kafka/producer/kafka.py
Current partitioners assume that the partitions are sorted according
to partition ID in all_partitions. However, this is not guaranteed
in the KafkaProducer implementation as the values that are passed
come from a set. Sets are not guaranteed to iterate values in any
particular order, so we need to sort the values before passing
them further along.
Before this change, the code depended on internal implementation of
Python interpreters. In CPython 3.5 and lower it seems that integers
are returned in sorted order from sets so the code appears to work.
In PyPy and CPython 3.6, sets and dictionaries preserve the order
of insertions [1] which means that the code may not work in these
environments (I have not tested this). As far as I could find,
the order of partitions used in this case is the …
=> Sort partitions before calling partitioner

kafka/consumer/group.py, test/test_client_async.py
KafkaConsumer can not resubscribe to new pattern without this fix because setting empty topics list always does not request metadata.
Does KafkaClient.set_topics need additional kwarg for request metadata?
PS. KafkaConsumer.unsubcribe calls set_topics with empty list. Is this problem?
=> Always request metadata when set empty topics list for KafkaClient

kafka/consumer/fetcher.py
Without that patch exception wasn't raised, instead consumer keeps retrying fetching.
=> Fix of exception raise in case of auto_offset_reset is set to None in KafkaConsumer

kafka/conn.py
Was a bit surprised to see this warning being thrown even though we're already on 2.7
According to the Python docs, the new SSL error classes were added in 2.7.9 and 3.3, so I updated the warning:
https://docs.python.org/3/library/ssl.html?highlight=ssl#ssl.SSLZeroReturnError
https://docs.python.org/2/library/ssl.html#ssl.SSLZeroReturnError
=> Make SSL warning list the correct Python versions

docs/install.rst
These days, anyone who needs these instructions should be using `pip`.
=> Remove non-pip install instructions

kafka/consumer/group.py
The Java consumer now defaults to 500 as of Kafka 0.10.1.0. Switch to this rather than `sys.maxsize` to reduce surprises since this library explicitly tries to mirror the Java library.
=> Default max_poll_records to Java default of 500

kafka/client_async.py, kafka/conn.py
This adds INFO logging for each BrokerConnection.close(), including the upstream error when available.
=> Log connection closes

kafka/client_async.py
The docs for the class params aren't showing up on ReadTheDocs.
As best I can tell, this is because the docstring was located under the `__init__` rather than the Class definition. So this reorders it to fix it. Not 100% positive that's the root cause, but I think it is.
=> Move docstring so it shows up in Sphinx/RTD

kafka/vendor/selectors34.py
when we use invoking self._select, python will pass self as select.select's first argument and we will get `TypeError: select() takes at most 4 arguments (5 given)`
=> use select.select without instance bounding

kafka/consumer/subscription_state.py
Raising `ValueError` from `SubscriptionState.assign_from_subscribed()`
always fails because there is used percent formatting of `TopicPartition`.
But `TopicPartition` is [namedtuple](https://github.com/dpkp/kafka-python/blob/master/kafka/structs.py#L59) with two elements and percent
formatting tries to unpack tuples, fails and raise exception:
`TypeError: not all arguments converted during string formatting`.
Converting to string first solves the issue.
=> Fix raise exception from SubscriptionState.assign_from_subscribed

kafka/client.py
@dpkp, this pull request is for people who may have the same issue as us #957.  
As SimpleClient is to be deprecated, I used BrokerConnection._sock directly instead of updating BrokerConnection to expose _sock.  Also `select` module is used directly.  You can update it if you think it is needed.
=> Use select to poll sockets for read to reduce CPU usage

kafka/protocol/offset.py
Kafka server protocol calls this timestamp, not time. 
See also  https://github.com/dpkp/kafka-python/pull/951#discussion_r96803189
Thankfully this struct isn't yet used internally in the code, so easy to correct it now.
=> time --> timestamp to match Java API

kafka/conn.py
This way it’s displayed in ReadTheDocs. It isn’t when it’s under `__init__`... see also #952
=> Move BrokerConnection docstring to class

kafka/protocol/commit.py
Adds the new structs that are used for #950
=> KIP-88 / KAFKA-3853: OffsetFetch v2 structs

test/test_conn.py
If we need better coverage we should just improve the mocked-socket test. External socket behavior is not consistent enough to rely on for testing (lots of false failures).
=> Drop bad disconnect test

kafka/consumer/group.py, test/test_consumer.py
=> Fail-fast on timeout constraint violations during KafkaConsumer creation

kafka/util.py, test/test_util.py
Start pruning some of the code that’s no longer used after the migration to structs.
=> Remove dead code

kafka/client.py, kafka/protocol/legacy.py, kafka/structs.py
Currently, Kafka Python has OffsetRequest_v1(It's name changed as ListOffsetRequest v1)
But there is no way to using this request. this is very helpful for searching offset by timestamp.
so, I add send_list_offset_request to request OffsetRequest_v1 and OffsetResponse_v1
and this feature only can use kafka 0.10.1.x or higher.
and, I missed test code, when I looked OffsetRequest test code, they are all skip annotation.
How do I add test for this feature?
Thanks.
```
from kafka import KafkaClient
from kafka.structs import ListOffsetRequestPayload
client = KafkaClient(hosts=['broker1:9092', 'broker2:9092', 'broker3:9092'])
reqs = []
reqs.append(ListOffsetRequestPayload("test2", 0, 1488161648929))
v = client.send_list_offset_request(reqs)
print(v)
```
=> Add send_list_offset_request for searching offset by timestamp

kafka/producer/kafka.py
Users can pass some binary data that will cause UnicodeDecodeError if logging handler converts the log record to unicode (e.g. serializes it to JSON object). To the best of my knowledge using %r in the message template is the best way to avoid such kind of problems and quick research confirms that https://mail.python.org/pipermail/python-list/2009-July/542427.html
```python
In [1]: import zlib
In [2]: msg = 'value=%s' % zlib.compress('value')
In [3]: msg.decode('utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 7: invalid start byte
In [4]: msg2 = 'value=%r' % zlib.compress('value')
In [5]: msg2.decode('utf-8')
Out[5]: u"value='x\\x9c+K\\xcc)M\\x05\\x00\\x06j\\x02\\x1e'"
```
Fixes #910
=> Replace %s with %r in producer debug log message

kafka/client.py, kafka/consumer/group.py, kafka/coordinator/base.py, kafka/producer/base.py, kafka/producer/kafka.py
Got tired of scrolling, so I attempted to hyperlink the methods in Sphinx. 
I *think* this is the correct way to format things, but not 100% confident.
=> Add sphinx formatting to hyperlink methods

kafka/cluster.py
When a broker goes down and is removed from the cluster metadata, the current client would still retain the old broker information. This causes KafkaClient.least_loaded_node to sometimes choose a broker which no longer exists, leading to an immediate connection failure and another metadata refresh. In rare cases this could lead to a vicious cycle of metadata refresh while other connections may have pending in-flight-requests and therefore get low priority from least_loaded_node.
This PR changes the metadata response handling to fully reset the internal brokers list and avoid this problem. Note that this does not remove existing BrokerConnection objects from the KafkaClient._conns dict.
=> Drop old brokers when rebuilding broker metadata

kafka/coordinator/base.py
Existing group coordinator discovery code triggers a metadata refresh on any error other than a small whitelist (GroupCoordinatorNotAvailableError). This PR drops the whitelist in favor of a simple check for the invalid_metadata attribute on retriable kafka errors.
This is expected to reduce unneeded metadata refreshes when, for example, the socket is simply still connecting (NodeNotReadyError).
=> Dont refresh metadata on failed group coordinator request unless needed

kafka/conn.py
I noticed during testing that a socket disconnect during ssl handshake could lead to an unhandled error.
=> Catch socket errors during ssl handshake

kafka/conn.py
The blackout calculation relies on conn.last_attempt to determine how long before attempting a reconnect. In order to correctly blackout disconnected nodes, we need to set the timer on disconnect.
=> Mark last_attempt time during connection close to fix blackout

kafka/conn.py
Intended to include the node_id with BrokerConnection log messages. This can help differentiate between bootstrap connections and normal cluster connections to the same host/port.
=> Include the node id in BrokerConnection __repr__

kafka/conn.py
Semantically this makes more sense, and it should improve logging. Also note that invalid_metadata is False for Cancelled but was True for ConnectionError.
=> Just cancel in-flight-requests when connection closed without error

kafka/client_async.py, kafka/conn.py, kafka/consumer/fetcher.py, kafka/consumer/group.py, test/test_consumer_integration.py, test/test_fetcher.py
Also added a check for api_version=(0, 10, 1) and MetadataRequest_v2
[KIP-74](https://cwiki.apache.org/confluence/display/KAFKA/KIP-74%3A+Add+Fetch+Response+Size+Limit+in+Bytes)
NOTE: Depends on PR #974
=> Added `max_bytes` option and FetchRequest_v3 usage.

kafka/consumer/group.py, test/test_consumer_group.py
Originally I thought enabling consumer group behavior by default would be useful. But having watched issue after issue opened following confusion about group semantics, I think it is time to drop the default. I note that the kafka-console-consumer.sh script uses a random consumer group if one is not supplied. This is basically the same thing -- subsequent runs of the same "script" will behave as if there were no rebalancing and no commits.
This should help avoid confusion caused by (1) join group delays due to session timeouts after ctrl-C or other unclean consumer shutdown, (2) no duplicate message consumption after restart due to auto commit.
=> Disable default consumer group

kafka/coordinator/base.py
The current code to drain requests to the coordinator node could still cause an unhandled coordinator_dead call. This PR should prevent any dead coordinators from slipping through the cracks.
=> Avoid unknown coordinator after client poll

kafka/coordinator/base.py
This PR attempts to reduce error logging caused by _failed_request, primarily for JoinGroupRequest. Also included are snippets for SyncGroupRequest and HeartbeatRequest, though logically these should be less likely to trigger as the coordinator connection should already be primed by a successful JoinGroupRequest the time those requests are sent.
=> Short-circuit group coordinator requests when NodeNotReady

kafka/protocol/message.py, test/test_protocol.py
On my laptop this PR improves consumer performance (when CPU bound) by about 33% . There are a lot of improvements that could be made to encoding / decoding, but this was by far the lowest hanging fruit. There is no reason to re-encode a message just to re-calculate its crc. By calculating the "validation" crc against the original bytes, we can avoid the extra CPU cost and speed up overall consumption.
=> Avoid re-encoding for message crc check

docs/index.rst, docs/install.rst, kafka/codec.py, test/test_buffer.py, test/test_codec.py, test/test_producer.py, tox.ini
=> Free lz4 decompression context to avoid leak

kafka/client.py, kafka/client_async.py, kafka/conn.py, kafka/protocol/admin.py, kafka/protocol/api.py, kafka/protocol/commit.py, kafka/protocol/fetch.py, kafka/protocol/group.py, kafka/protocol/metadata.py, kafka/protocol/offset.py, kafka/protocol/produce.py, test/test_client_async.py, test/test_conn.py
A minor refactor that uses `abc` to enforce some basic request / response class requirements. I've also moved the logic used to check whether a request generates a response (i.e., ProduceRequest w/ acks=0) to the Request class. This will help with further client + protocol refactoring.
=> Derive all api classes from Request / Response base classes

README.rst
There is a bug in lz4tools. https://github.com/dpkp/kafka-python/issues/1047
Do not suggest using it in the README.rst.
=> Update README: Prefer python-lz4 over lz4tools

kafka/client_async.py
Previously Sphinx was auto-linking to `poll()` in `KafkaConsumer`, so made the link explicit.
=> Fix poll() hyperlink in KafkaClient

kafka/client_async.py
During a travis test run, `producer.close()` triggered an unhandled exception during client.wakeup(). The exception was a Broken Pipe during send on the wakeup socketpair. I am not sure what caused the other side of the socketpair to close, but I think we should catch the error and log a warning rather than crash.
=> Catch socket.errors when sending / recving bytes on wake socketpair

kafka/client_async.py, test/test_client_async.py
Following upstream KAFKA-4024, this revision prevents connecting to multiple nodes simultaneously during metadata refresh when the least loaded node(s) is/are not currently connected.
KAFKA-4024 also includes a fix to avoid potentially waiting for the retry_backoff_ms period before refreshing topic metadata after the topic subscription changes. That change is not included here.
=> Avoid multiple connection attempts when refreshing metadata

kafka/client_async.py, kafka/conn.py, kafka/producer/kafka.py, test/test_client_async.py
=> Timeout idle connections via connections_max_idle_ms

kafka/conn.py
BrokerConnection currently raises a socket exception if dns resolution of broker metadata fails. This error is typically unhandled by application code and causes a hard crash. In many cases, this error is recoverable after short delay (temporary dns infrastructure problems) and/or refresh metadata (configuration errors). This PR changes the response to dns lookup errors to no longer raise an exception and instead just log a warning.
=> Warn on DNS lookup failures

kafka/producer/record_accumulator.py
=> Improve error message when expiring batches in KafkaProducer

kafka/producer/kafka.py, kafka/producer/record_accumulator.py
https://github.com/dpkp/kafka-python/issues/1094
- Renamed `TimeoutException` to `KafkaTimeoutError`. Outside of the scope of original PR, let me know if I should pull this out.
- Catching both timeout and done assertion checks. My thinking was that if the user did not specify a timeout we would never hit the done check. If the user did specify a timeout and the done check fails it seems reasonable to consider it a timeout. I might be making too large of an assumption here.
=> Flush timeout raises timeout

servers/0.11.0.0/resources/kafka.properties, servers/0.11.0.0/resources/log4j.properties, servers/0.11.0.0/resources/zookeeper.properties, test/test_consumer_group.py, test/test_consumer_integration.py, test/test_producer.py
The resources are identical to 0.10.1.1 resources, except for `offsets.topic.replication.factor`. This setting must be equal or less than the total number of brokers or kafka will not start the GroupCoordinator properly. Since we run most of our tests against a single broker, I reduced it to `1`.
The other issue I found during testing was that 0.11.0.0 behaves slightly differently to the fetchrequest max_bytes parameter. For v3, the request-level max_bytes is always "soft" -- meaning that some data will always be returned even if slightly larger than max_bytes. In 0.10+ the minimal amount of data was a single message. In 0.11 it is a full MessageSet. So tests that had relied on only a single message response need to be updated. In addition, the partition-level max_bytes parameter in v0, …
=> Add fixture and test support for 0.11.0.0

kafka/coordinator/base.py
When testing 0.11.0.0 I noticed that KafkaConsumer would enter a tight CPU loop if the broker's group coordinator api returned retriable errors.
=> Backoff on unavailable group coordinator retry

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py
=> KIP-144: Exponential backoff for broker reconnections

kafka/producer/kafka.py
Hit a problem with pytest hitting the atexit handler and waiting
for close() timeout forever at teardown.
This commit makes atexit close() equivalent to __del__ behavior,
namely using timeout of 0 for close() completion. If you need a
longer timeout you should be setting it explicitly.
=> producer: Set exit timeout to 0 for atexit handler to match __del__

kafka/coordinator/consumer.py
When we are using subscription by pattern change subscription is
called every metadata update even when nothing changes. It logs
warning every time topics are not changed. It creates unnecessary
noise in logs. I changed it to level info so it can be easily ignored
(I want to see only warnings from kafka client). Do you think this is
a right approach or I should check in `ConsumerCoordinator._handle_metadata_update`
that no topics has changed and not call `change_subscription` in 
this case? I would then need to change it in aiokafka too because I'm
using that.
=> change_subscription warning log to info

kafka/protocol/admin.py, kafka/protocol/commit.py, kafka/protocol/fetch.py, kafka/protocol/group.py, kafka/protocol/metadata.py, kafka/protocol/offset.py, kafka/protocol/produce.py
This PR includes protocol definitions for apis that have new versions in 0.11.0.0. The majority of these are for the addition of throttle_time_ms to api responses. I have not plumbed any of them into the client code. I also did not add new APIs (TXN apis, Create/Describe/Delete ACLs, Describe/Alter Configs, etc). These updates are from `clients/src/main/java/org/apache/kafka/common/protocol/Protocol.java` on tag `0.11.0.0-rc1` from https://github.com/apache/kafka
=> Protocol updates for 0.11.0.0

kafka/producer/kafka.py
Add note, that `max_in_flight_requests_per_connection>1` may change order or messages to `max_in_flight_requests_per_connection` description. I know, that `retries` mentions this, but often you only change max_in_flight_requests_per_connection without reading all option descriptions.
=> Additional note about order to docs

kafka/conn.py
this is the first version, please have a look on it
=> added gssapi support (Kerberos) for SASL

kafka/coordinator/base.py
Seems like copy-paste typo.
Use Max() instead of Avg() for join-time-max and sync-time-max metrics.
=> Use for join-time-max and sync-time-max metrics Max() 

kafka/producer/record_accumulator.py
time.time() is seconds since epoch, and the deltas are also calculated
in seconds
=> Fix batch expiry messages to state seconds

kafka/errors.py
Checked the old client, and the error was retriable there (https://github.com/dpkp/kafka-python/blob/master/kafka/errors.py#L505), so decided there's no need to skip the retry in v0.8 brokers.
=> Make UnknownTopicOrPartitionError retriable error

kafka/conn.py
I saw this traceback as a recurring loop in my client which uses KafkaConsumer:
...
File "/usr/lib/python3.5/site-packages/kafka/client_async.py", line 491, in send
if not self._maybe_connect(node_id):
File "/usr/lib/python3.5/site-packages/kafka/client_async.py", line 368, in _maybe_connect
conn.connect()
File "/usr/lib/python3.5/site-packages/kafka/conn.py", line 355, in connect
if self._try_handshake():
File "/usr/lib/python3.5/site-packages/kafka/conn.py", line 420, in _try_handshake
self._sock.do_handshake()
File "/usr/lib64/python3.5/ssl.py", line 996, in do_handshake
self._sslobj.do_handshake()
File "/usr/lib64/python3.5/ssl.py", line 641, in do_handshake
self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:720)
Based on: …
=> conn: Catch ssl.EOFErrors on Python3.3 so we close the failing conn

kafka/consumer/fetcher.py
Raise AssertionError when decompression unsupported.
=> Raise AssertionError when decompression unsupported. Fix #1033

kafka/conn.py, kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/protocol/offset.py, kafka/structs.py, test/test_consumer_integration.py, test/test_fetcher.py
Still needs to group by nodes and send in parallel.
=> Added support for offsets_for_times, beginning_offsets and end_offsets APIs.

kafka/coordinator/consumer.py
This addresses the issue raised in #1173 , namely that the internal metadata snapshot -- used to check whether the group should rebalance when subscribed topic metadata changes -- is initialized as empty and this causes the first set of metadata to always force a rebalance, even if the metadata didn't actually change.
=> Initialize metadata_snapshot in group coordinator

kafka/client_async.py, kafka/conn.py, kafka/protocol/frame.py, kafka/protocol/message.py
This is a first step towards #560 . Refactors the internals of BrokerConnection to separate handling network IO from decoding responses. The initial refactor only addresses recv . Refactoring send will be tackled in a separate PR. The eventual goal is to separate the base protocol parser into an isolated class that is completely independent of network IO.
=> BrokerConnection receive bytes pipe

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/sender.py
Thank you for creating and maintaining this excellent package! I was reading through the code today just trying to get a better sense of the internals, and found a few unused imports. Please consider this PR to remove them.
=> Remove a few unused imports

kafka/consumer/group.py, test/test_consumer_integration.py
- Remove beginning_offset and end_offset version limit because the kafka service of lower versions can get accurate offsets in these two functions.
Our discussion is in [#1199](https://github.com/dpkp/kafka-python/pull/1199)
=> remove beginning/end offsets request version limit

kafka/client.py, test/test_client.py, test/test_conn.py, test/test_fetcher.py, test/test_sender.py
Using mutable types for default args is typically a no-no unless their
surprising behavior is being explicitly abused, for an explanation see:
http://effbot.org/zone/default-values.htm
Note to reviewers: This is just a find-and-replace of `=[]` with `=()` to see if the tests pass. 
Possibly some of these arguments aren't actually used and could simply be removed, for example 
the test files. If you notice any of these, please comment and I will update the PR.
Fix #1212
=> Stop using mutable types for default arg values

kafka/conn.py
=> Remove raw traceback

kafka/conn.py
I found some small fixups while investigating other SASL issues.
=> Minor SASL documentation and logging fixes

kafka/coordinator/consumer.py
If the group leader somehow gets in a state that it has an empty partition assignment, then `self._assignment_snapshot` will be `{}` which evaluates to `False`. So `self._subscription.mark_for_reassignment()` will never be triggered, even if `self._assignment_snapshot != self._metadata_snapshot`. 
Here is the relevant upstream Java code:
https://github.com/apache/kafka/blob/c5d26c4829583c95af7ca9e961a4d3954f8e09eb/clients/src/main/java/org/apache/kafka/clients/consumer/internals/ConsumerCoordinator.java#L197
Fixes the symptoms of #1237 although I suspect there's an additional bug in that case that triggers the condition of the the group leader getting an empty partition assignment.
I'm hesitant with this fix because I still don't fully understand the race condition that results in the …
=> Explicitly check for `None` rather than False

kafka/consumer/subscription_state.py, test/test_substription_state.py
As described in #961, the consumer does not check whether topic names are valid. It does however check if the topic name is a string.
This PR adds a check according to the current kafka source:
https://github.com/apache/kafka/blob/39eb31feaeebfb184d98cc5d94da9148c2319d81/clients/src/main/java/org/apache/kafka/common/internals/Topic.java#L29
That means:
- A Topic name must not be empty
- It must not be `.` or `..`
- It must be shorter than 250 characters
- It must consist only of `a-z`, `A-Z`, '0-9', `.`, `-` and `_`
=> Add method to ensure a valid topic name

README.rst, kafka/consumer/group.py, kafka/producer/kafka.py
I've never taken the time to experiment with them because they weren't documented, so decided to fix that.
There were a number of distinct changes, so I tried to keep them contained within separate commits so we can easily drop any that aren't wanted... probably easiest to review as distinct commits as well.
For example, I'm not sure if the Sphinx warning syntax will show up properly on RTD or not, as I'm not sure how to build the docs locally.
=> Expand metrics docs

.travis.yml, build_integration.sh, servers/0.11.0.1/resources/kafka.properties, servers/0.11.0.1/resources/log4j.properties, servers/0.11.0.1/resources/zookeeper.properties, test/fixtures.py
Also updated test.fixtures to use 0.11.0.1 by default if KAFKA_VERSION is not set. Previously the default was 0.8.0
=> Update to 0.11.0.1 for travis test fixture

kafka/conn.py, kafka/errors.py, kafka/protocol/parser.py
Further work toward Issue #560 . Following from PR #1032, this moves the translation of api request/response events to and from network IO bytes into an independent class, KafkaProtocol. 
This class is intended to be reusable between different approaches to socket handling / networking. This approach should also enable simplified unit testing of protocol-level code (though actual test updates are left for future PRs).
=> Use KafkaProtocol to handle serialization/deserialization of api events

kafka/conn.py
SASL/GSSAPI authentication may require several rounds of token exchange with the broker. We need to continue the process until the gssapi context is marked complete or until an exception is raised. Network I/O errors are caught and can be retried; otherwise all other exceptions, including GSSAPI errors, will be raised directly to the user.
Fixes #1189
=> Always wait for completion during SASL/GSSAPI authentication

kafka/conn.py
This PR improves error handling when using SSL and/or SASL connections.
=> Check for disconnects during ssl handshake and sasl authentication

kafka/consumer/fetcher.py, test/test_fetcher.py
=> KAFKA-3977: defer fetch response parsing and raise exceptions to user

kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, test/test_coordinator.py
The coordinator future and associated callback chain is a requirement for the KAFKA-3888 implementation of background autocommit thread.
=> KAFKA-4034: Avoid unnecessary consumer coordinator lookup

Makefile, requirements-dev.txt
With this, users which are less familiar with the project can easily build, generate docs and run tests.
=> Add a Makefile

kafka/conn.py
This PR fixes three bugs in sasl handshake processing: First, after #1230 _recv() does not handle futures / in-flight-request processing. We need to call self.recv() if we want callbacks to be triggered automatically. Second, it is possible that recv() may catch a network error and close the connection. This will reset _sasl_auth_future and so we need to validate that it is not None before checking if it failed or succeeded. Third, when processing the SaslHandShakeResponse we should validate that the configured sasl_mechanism is listed as enabled in the handshake response.
In addition, I have consolidated the socket send routine into a single private method, _send_bytes_blocking(data).
Fixes #1255
=> Fix SASL authentication bugs

kafka/consumer/group.py
Fix `seekToBeginning`/`seekToEnd` Java syntax into python
Opened as PR rather than just merging as I'm not sure I got the sphinx syntax right and don't have laptop available to build the docs right now... I created this PR by editng the file using github's web ui.
=> Fix docstring

kafka/conn.py
I haven't tested this -- I do not have a kerberos system available. But I believe it fixes the AttributeError in #1259 as well as generally cleaning up the gssapi code to be more 'pythonic'
=> Cleanup gssapi code; fix bug report re AttributeError.

kafka/consumer/group.py, kafka/producer/kafka.py
updated producer and consumer configs to resolve assertion error when using sasl kerberos service name
see #1263
=> updating configs to resolve #1263

kafka/client_async.py
Be pedantic about checking for identity rather than equality to avoid issues like #1237 / 411bc08f214b7afc36f11bde2047096c06467088
Noticed while reviewing #1266
=> Explicitly check for None rather than falsey

kafka/client.py, kafka/client_async.py, kafka/conn.py, test/test_client.py
This is a small refactor to how response callbacks are processed. It is designed to separate the callback chain processing from the network processing code. This will allow us to use a threading lock around client networking that can be released before processing callbacks to reduce the risk of deadlock. This approach is derived from KAFKA-3888 / KIP-62 (background heartbeat thread).
=> Move callback processing from BrokerConnection to KafkaClient

example.py
Added better control over threads/processes, making them shutdown cleanly before the program terminates. Switched from the iterator to poll() style to do it.
Should solve this issue: https://github.com/dpkp/kafka-python/issues/1130
=> Added controlled thread shutdown to example.py

kafka/producer/future.py, kafka/producer/record_accumulator.py, kafka/record/legacy_records.py, kafka/record/memory_records.py, test/record/test_legacy_records.py, test/test_producer.py
Tried to fix #1270 and found, that it did not work properly in the first place. Was a bug in FutureRecordMetadata, that ignored timestamp=-1 being returned from the broker.
Also minor fixes include:
* Avoid getting current timestamp if magic==0 (broker <= 0.9), as it's not needed anyway. Will return -1 for this case in ```RecordMetadata```.
* Fixed timestamp error message if it's of improper type.
* Added more tests for LegacyBatch
* Added integration test for correct RecordMetadata fields, including `checksum`
=> Fix timestamp not passed to RecordMetadata

servers/1.0.0/resources/kafka.properties, servers/1.0.0/resources/log4j.properties, servers/1.0.0/resources/zookeeper.properties, test/fixtures.py
1.0.0 RC2 is available for testing here: http://home.apache.org/~guozhang/kafka-1.0.0-rc2/
When testing locally I noticed that the logging patterns that our test.fixture code waits for have changed. This PR updates the pattern to support the new format w/o breaking old format, and adds resources necessary to get zookeeper and kafka 1.0.0 running. Once the final version is released we can add to .travis.yml for automated testing.
=> Add fixture support for upcoming 1.0.0 broker release

kafka/conn.py
Fixes #1276 and #1277 
Unfortunately we still have zero test coverage on gssapi. Any help writing tests would be appreciated!
=> Fix more gssapi errors

kafka/coordinator/base.py, test/test_coordinator.py
=> Handle lookup_coordinator send failures

kafka/conn.py
=> Use socket timeout when blocking on send/recv

kafka/consumer/fetcher.py, kafka/consumer/group.py
These values refer to Megabytes, not Megabits.
Fix #1295
=> Use correct casing for MB

kafka/protocol/types.py
Bug 1:
When `value` is `None`, trying to call `len(None)` throws an exception.
Bug 2:
When `len(value) <= 100`, the code currently prints `b''` rather than
`value`.
@asdaraujo I cherry-picked this commit from your other PR, as I want to make sure fixes for both of these issues land, and I think the pytest will be a longer journey. I marked you as the commit author to give you credit for finding this issue, if you prefer otherwise I can change it.
@tvoinarovskyi can you review since you wrote this code originally? You normally pay attention to these kinds of details and sometimes use techniques I'm not familiar with, so want to make sure this isn't something you did on purpose...
=> Fix two bugs in printing bytes instance

test/fixtures.py
@dpkp, I think the current errors with the Travis build may be because the VM have IPv6 disabled and since the fixtures are forcing the use of IPv6 the Kafka broker cannot bind to a valid address. If this is indeed the case, however, I'm not sure what happened recently that caused builds start failing.
I had a look at the `KafkaFixture` code and saw the comment saying that if the broker binds to an IPv4 address, then "kafka-python will attempt to connect on ::1 and fail".
I'm not sure why that's the case. I checked the code and couldn't find an explanation. Maybe this has been changed since?
I'm also not quite sure what's the use of the bracket notation for the broker address (e.g. `[::1]`). I couldn't find a reference to it in the Kafka documentation. I noticed that it doesn't work with …
=> Change fixture default host to localhost

kafka/client_async.py, kafka/conn.py, kafka/producer/kafka.py, kafka/producer/sender.py
Use "9999999999" or "999999999" for max value might be not proper. This is a little bit misleading and might cause potential issues.
=> use python standard max value

kafka/conn.py, test/test_conn.py
Fix #1306 by refactoring dns lookup / getaddrinfo handling in BrokerConnection.
The reported failure appears to be caused when DNS lookup fails or returns no data. In this case we were caching the empty gai data and never performed another DNS lookup. This prevented the client from "discovering" the broker again when it came back online. We also were not properly handling the connection failure to support reconnect backoff timers.
=> Refactor dns lookup in BrokerConnection

kafka/protocol/types.py
Stop shadowing the word `error` because we want to know what the specific exception message was.
Also give more details on exactly which value failed. We don't know who submitted the value, but perhaps it's unique enough that we can debug it better.
Fix #1318
=> Give better struct errors

requirements-dev.txt, tox.ini
This is a short-term fix to avoid failing all tests. After landing we should investigate the root cause and fix so that we can continue with newer releases for these libraries.
=> Pin pylint and lz4 to avoid breaking tests

kafka/client_async.py, kafka/conn.py, kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/coordinator/heartbeat.py, kafka/errors.py, kafka/protocol/group.py, test/test_client_async.py, test/test_consumer.py, test/test_consumer_group.py, test/test_consumer_integration.py, test/test_coordinator.py
This PR implements KAFKA-3888 (including related KAFKA-4431). It adds significant complexity and relies on managing shared mutable state, which I really don't feel great about. Nonetheless, I wanted to put this up so that folks can see where it's at and possibly test out independently.
One remaining issue: address default configuration changes when broker does not support rebalance timeout (only session timeout). 
ref #948 / includes #1258 
See also KAFKA-4160
=> KAFKA-3888 Use background thread to process consumer heartbeats

kafka/producer/kafka.py
The original intent was to catch API exceptions (errors returned by the
broker when trying to produce a message) and delegate them to the
messages' futures. This is copied from the Java producer.
However, we were accidentally catching all exceptions, thereby hiding
exceptions from users unless they explicitly check the result of the
future. Much better to raise client-side errors directly in the
foreground so the user is immediately aware of them and can decide how
to handle.
Fix #1274
=> Raise non-API exceptions

kafka/conn.py
Returned data was lost, thus `if data != b'\x00\x00\x00\x00':` always fails .
=> Fix typo in _try_authenticate_plain

kafka/client_async.py, kafka/conn.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/util.py
After digging into #1331 a bit it I found a few issues:
(1) heartbeat thread is not stopped unless KafkaConsumer is closed explicitly (or python interpreter exits).
(2) most connection objects have a circular reference preventing garbage collection prior to interpreter shutdown
(3) the client object also has a circular reference preventing gc prior to shutdown
This PR should fix these issues by using weakrefs to break circular references and by shutting down local resources like the heartbeat thread during gc via `__del__`
It appears that there are still circular references preventing gc of KafkaMetrics and possibly SubscriptionState. These do not prevent the consumer, coordinator, client, or connection objects from being cleaned up, so I'm going to leave further fixes for a later PR.
=> Improve KafkaConsumer cleanup

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py
This addresses the issue discussed in #1315 by repeatedly reading from a non-blocking socket until there are no available bytes remaining. The current code reads only once per select / poll, which causes excessive poll looping when the broker sends many small packets (see #1315 for more discussion).
=> Read all available socket bytes

kafka/coordinator/base.py, test/test_coordinator.py
=> Fix coordinator join_future race condition

kafka/conn.py, test/test_conn.py
While debugging a heartbeat thread issue I noticed that BrokerConnection reconnects do not always honor the reconnect backoff. This PR updates the lowest level call (`connect()`) so that it will only start a new connection after the backoff period.
=> Honor reconnect_backoff in conn.connect()

kafka/consumer/fetcher.py
I noticed this failure in a failed travis run. If we attempt to remove a partition that is not currently fetchable, the set will raise a KeyError. To avoid, we test that the element is in the set before removing it.
=> Avoid KeyError when filtering fetchable partitions

test/test_consumer_group.py, test/test_coordinator.py, test/test_producer.py
Miscellaneous test fixups that I accumulated while working on other PRs.
=> Minor test cleanups

kafka/coordinator/base.py
Another set of small improvements that I stashed while working on other PRs. To help with log analysis we can name the heartbeat thread using the consumer group_id .  I've also added a short timeout to the internal heartbeat poll to avoid tight loops.
=> Name heartbeat thread with group_id; use backoff when polling

kafka/producer/kafka.py
According to the [Kafka Document](http://kafka.apache.org/documentation.html#producerconfigs) and the usage in [client_async.py](https://github.com/dpkp/kafka-python/blob/master/kafka/client_async.py) ，the config  `reconnect_backoff_max` should be `reconnect_backoff_max_ms` 
: )
=> fix reconnect_backoff_max_ms default config bug in KafkaProducer

kafka/client_async.py
When running Python code with PYTHONOPTIMIZE=1 assertions are removed. Needless to say, an assertion should never have a side effect that is critical for the program's execution. @dpkp You seem to have ignored the following: https://github.com/dpkp/kafka-python/issues/1184 but I was getting the same symptoms and it took quite some time to figure out the cause.
=> Remove assertion with side effect

AUTHORS.md, kafka/conn.py
Due to differences in byte string handling between Python 2 and 3, this fix is required to be able to use Kerberos authentication with Python 3
=> Fix for Python 3 byte string handling

.travis.yml, Makefile, build_integration.sh, servers/0.11.0.2/resources/kafka.properties, servers/0.11.0.2/resources/log4j.properties, servers/0.11.0.2/resources/zookeeper.properties, test/fixtures.py
This switches 0.11 integration tests to use the latest 0.11 patch release, 0.11.0.2.
=> Use 0.11.0.2 kafka broker for integration testing

tox.ini
Opening a PR to check if tests pass with the new version. If so, we'll want to bump `requirements-dev.txt` as well, since it was also pinned in c2331db80c31d5222d1c267b8a0de5ce58b7f6f0.
Many thanks to @jonathanunderwood for his diligent work here: https://github.com/dpkp/kafka-python/issues/1021#issuecomment-359161985
=> Stop pinning lz4

requirements-dev.txt, tox.ini
=> Use latest pytest 3.4.0, but drop pytest-sugar due to incompatibility

requirements-dev.txt
We stopped pinning it in tests here: https://github.com/dpkp/kafka-python/commit/4dc0899411a8de4eac94481ed719ecdc975c3bb4
So now bumping the pinned version to the latest release.
=> Bump `lz4` in `requirements-dev.txt`

kafka/cluster.py, kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/consumer/subscription_state.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, test/test_coordinator.py
=> KAFKA-3949: Avoid race condition when subscription changes during rebalance

kafka/consumer/fetcher.py, test/test_fetcher.py
Fixes #1214 w/ test for #1290 regression
=> Avoid consuming duplicate compressed messages from mid-batch

kafka/conn.py, kafka/protocol/admin.py, kafka/protocol/fetch.py, kafka/protocol/group.py, kafka/protocol/metadata.py, kafka/protocol/produce.py
I scanned through the 1.0.0 api protocol support and added most that were missing. This does not include changes to admin apis, just the main producer/consumer clients.
=> Add Request/Response structs for kafka broker 1.0.0

kafka/protocol/types.py
This should reduce confusion in the off-chance that `str` is overridden.
Thanks to Taras for the suggestion: https://github.com/dpkp/kafka-python/pull/1320/files#r155716948
=> Use raw in case string overridden

.gitignore, test/fixtures.py, test/test_consumer_integration.py, test/test_producer.py, test/testutil.py
Most travis test runs hit at least one timeout -- typically when attempting to start up kafka broker fixtures. This PR increases timeouts in an attempt to reduce false positives and increase overall confidence in our travis test results.
=> Increase some integration test timeouts

kafka/coordinator/consumer.py
The consumer poll is stuck due to long timeout when there is no more partition for it.
Actually, in function commit_offsets_async(), passing 0 as timeout into client.poll() is the very action the official Java source code does.
=> Fix consumer poll stuck error when no available partition

tox.ini
No longer necessary since pytest-catchlog has been merged into pytest's core.
This commit addresses the following warning in pytest output:
pytest-catchlog plugin has been merged into the core, please remove it from your requirements.
Fixes #1379
=> Removed pytest-catchlog dependency

kafka/protocol/__init__.py, kafka/protocol/admin.py
I've been using it for some time in a personal project.
Protocol should match:https://github.com/apache/kafka/blob/1.0/clients/src/main/java/org/apache/kafka/common/requests/CreatePartitionsRequest.java and  https://github.com/apache/kafka/blob/1.0/clients/src/main/java/org/apache/kafka/common/requests/CreatePartitionsResponse.java
=> Add Admin CreatePartitions API call

kafka/consumer/group.py
`ConsumerCoordinator.time_to_next_poll()` returns seconds, so need to convert to milliseconds.
Fixes https://github.com/dpkp/kafka-python/issues/1383
=> Correctly respect timeouts in consumer poll interface

docs/install.rst, kafka/record/util.py, test/record/test_util.py, tox.ini
@dpkp @jeffwidman Hehe, I'm an idiot for this =) So, here I was pushing my butt to accelerate varint implementation, but did not look properly at the profiler.
Long story short, while accelerating the V2 implementation for `aiokafka` I found that `_crc32c.py` is super slow and takes more time for 1 call than 100 `append`. So as a fast fix I propose to use https://github.com/ICRAR/crc32c if available on the system. I will look into `_crc32c.py` script later to make it a bit faster.
Benchmark without HW crc32:
```
.....................
batch_read_v0: Mean +- std dev: 1.42 ms +- 0.03 ms
.....................
batch_read_v1: Mean +- std dev: 1.44 ms +- 0.03 ms
.....................
batch_read_v2: Mean +- std dev: 3.10 ms +- 0.06 ms
```
With HW crc32:
```
.....................
batch_read_v0: …
```
=> Use hardware accelerated CRC32C function if available

kafka/client.py, kafka/client_async.py, pylint.rc, test/conftest.py, test/fixtures.py, test/test_client_integration.py, test/test_consumer_integration.py, test/test_failover_integration.py, test/test_producer_integration.py, test/testutil.py, tox.ini
In preparation for the changes I'll need to make to the integration tests to cover the GSSAPI authentication changes in PR #1283, I had to make a few changes to the existing test cases, which were written using unittest.TestCase.
After some discussions with @dpkp and @jeffwidman I decided to first move those test cases to pytest, which is the preferred test framework for the project.
=> Integration tests migration to pytest framework

kafka/producer/kafka.py
Unfortunately 1.4.x broke with this because it's accidentally sending the raw key and value instead of serialised byte strings.
=> Fix byte size estimation with kafka producer

kafka/consumer/group.py
Add validation to avoid cryptic error reported in #1387
=> Validate max_records in KafkaConsumer.poll

test/test_consumer_group.py, test/test_consumer_integration.py, test/test_producer.py
Eventually we should get a context manager interface, but for now we should just take care to close the consumer instances to avoid lingering heartbeat threads during long test runs.
=> Close KafkaConsumer instances during tests

kafka/conn.py, test/test_conn.py
=> Fix BrokerConnection.connection_delay() to return milliseconds

kafka/conn.py, test/test_conn.py
Separating this from #1411. The underlying issue is that KafkaClient checks whether the broker metadata has changed when deciding whether to "recycle" an existing BrokerConnection or not (see `_maybe_connect`). The check examines .host and .port directly, which means that we are creating false positives when we assign new resolved values to these attributes. This means that we are not recycling BrokerConnection objects the way we want to at best, and at worst it means that we are not dropping the objects before trying all possible resolved connection addresses.
=> Make BrokerConnection .host / .port / .afi immutable

kafka/conn.py
Separated from #1411 -- this is a simple fix to hopefully avoid leaking fds.
=> Close leaked selector in version check

kafka/codec.py, tox.ini
Add support for https://github.com/Iotic-Labs/py-lz4framed
=> Support alternative lz4framed

kafka/conn.py
Separated from #1411 . This PR prevents prematurely backing off when trying to connect to a multi-address host. We should only add a backoff delay if all available addresses fail.
=> Only increase reconnect backoff if all addrinfos have been tried

kafka/conn.py
Separated from #1411 . It is fairly common when handling a connection error for us to call `self.close(error)` inside BrokerConnection, return an error to the caller, and for the caller -- usually KafkaClient -- to call conn.close() again. Right now this causes connection errors to be double logged, which can seem strange. The PR simply checks whether the connection is already disconnected, and if so it does nothing. We assume that the only way to get a BrokerConnection object into the disconnected state is via `close()`
=> Short-circuit BrokerConnection.close() if already disconnected

kafka/client.py, kafka/client_async.py, kafka/conn.py, test/conftest.py, test/test_client_async.py
This PR adds a blocking connect to BrokerConnection that will attempt to connect to all ip/ports found via a single dns lookup. We can use this during bootstrap and version probes to handle brokers that advertise a hostname that has multiple interfaces but the broker only listens on one of them. This can happen when a host has both an IPv4 and an IPv6 interface (but the kafka broker binds to only one of them). This will also help in contexts where the bootstrap_servers list includes a multi-address dns entry where not all results are available/healthy.
=> Add BrokerConnection.connect_blocking()

kafka/conn.py
Log connection completion at INFO (previously DEBUG), and lookup socket error code message when logging errors. (separated from #1411)
=> Connection logging cleanups

kafka/conn.py
Connection errors used to result in stack traces, so we filtered them out during version check. The newer error logging is less scary, and I think it would be better to continue logging during version check so that users can see what is happening if necessary.
=> Re-enable logging during broker version check

kafka/conn.py, test/test_conn.py
=> Connect with sockaddrs to support non-zero ipv6 scope ids

kafka/client_async.py, kafka/consumer/group.py, kafka/producer/kafka.py
Fixes #892 . As jeff notes, there is not a great reason to require that the api_version tuple configured by the user is in our predefined list. Our version checks generally look for `>` or `<` so any value that compares correctly should be fine.
=> Do not validate api_version against known versions

kafka/producer/kafka.py
=> Validate that serializers generate bytes-like (or None) data

kafka/coordinator/consumer.py
=> Remove old CommitFailed error message from coordinator

test/test_consumer_integration.py, test/test_producer_integration.py
Small PR to fix running unit tests locally w/o starting brokers.
=> Fix skipped integration tests if KAFKA_VERSION unset

kafka/coordinator/base.py
See KAFKA-4777 -- if all brokers are down, the lookup_coordinator future will fail immediately. In that case we want to backoff before trying again.
=> Check for immediate failure when looking up coordinator in heartbeat thread

docs/simple.rst, kafka/producer/base.py, kafka/producer/keyed.py, kafka/producer/simple.py, test/test_failover_integration.py, test/test_producer_integration.py, test/test_producer_legacy.py
`async` is a reserved word in python 3.7. I've renamed the SimpleProducer async to `async_send` and updated the docs. Applications that pass `async=` will get a deprecation warning in the logs but we'll continue to allow for now by checking **kwargs.
Ref #1451
=> Change SimpleProducer to use async_send (async is reserved in py37)

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py
Fix #1458 . Also no need to keep 40000 as default for internal classes so I reduced to the KafkaProducer default of 30000 (the internal classes should almost never be relying on defaults since the outer classes will pass their own default values if user does not specify).
=> Fix KafkaConsumer docstring for request_timeout_ms default

kafka/coordinator/base.py
This PR changes logging to WARN for heartbeat state changes due to timeouts (session or poll timeouts). It also drops the waiting log message to TRACE since it can get quite noisy in longer debug logs.
=> Change levels for some heartbeat thread logging

kafka/protocol/admin.py
Hello,
While using your library to develop an Ansible module, I noticed that the current CreatePartitionsRequest_v0 is wrong since 'assignment' is an Array of Array of Int32 (see https://github.com/apache/kafka/blob/a553764c8b1611cafd318022d0fc4a34c861f6ba/clients/src/main/java/org/apache/kafka/clients/admin/NewPartitions.java#L37)
Tested in my project, everything is fine now.
Regards,
Stephen
=> Fix CreatePartitionsRequest_v0

kafka/conn.py
This should improve the BrokerConnection initialization performance avoiding call `selector.select(1)` without data to fetch in socket.
This PR is related to https://github.com/dpkp/kafka-python/issues/1468
=> Improve BrokerConnection initialization

kafka/coordinator/base.py
This is an attempt to address the deadlock issue described in #1461 . The first option discussed, delaying errback processing until after release of the client lock, would require a lot of work. I've instead tried to change the lock acquisition paths so that the coordinator never attempts to acquire the client lock after it holds the coordinator lock. This is done by either releasing the coordinator lock before calling functions that acquire the client lock, or by preemptively acquiring the client lock before acquiring the coordinator lock.
=> Always acquire client lock before coordinator lock to avoid deadlocks

kafka/protocol/admin.py
Hello,
I just saw issue #1326 is about those 2 apis. Since I already implemented and tested those in my Ansible library, I am opening this PR.
Regards,
Stephen
=> Added AlterConfigs and DescribeConfigs apis, fix #1326

kafka/codec.py
Kafka does not support LZ4 compression with dependent blocks
https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/record/KafkaLZ4BlockOutputStream.java#L343
This issue was first noticed when encoding larger-than-usual messages in our application.
This change appears to solve the problem by enforcing compression with independent blocks in the underlying LZ4 package.
=> Force lz4 to disable Kafka-unsupported block linking when encoding

kafka/client.py, kafka/client_async.py, kafka/conn.py, kafka/errors.py, kafka/producer/base.py, test/test_client.py, test/test_conn.py, test/test_failover_integration.py
In Python3, `ConnectionError` is a native exception. So rename our custom one to `KafkaConnectionError` to prevent accidentally shadowing the native one.
Note that there are still valid uses of `ConnectionError` in this code.
They already expect a native Python3 `ConnectionError`, and also already
handle the Python2 compatibility issues.
=> Stop shadowing `ConnectionError`

kafka/cluster.py
If a valid broker in the cluster has no partitions, it will return `None` rather than an empty set.
This was surprising behavior to me, I expected a broker that exists but has no partitions would return an empty set. So I'm not sure if it's better to document the current behavior, or change this to `get(broker_id, set())`.
Similarly documented a few other methods that sometimes can return `None`.
=> Document methods that return None

kafka/cluster.py, kafka/errors.py, test/test_cluster.py
Fix for #1494 . The MetadataResponse should be ignored and treated as a failure if the broker list is empty (same as the java client).
=> Ignore MetadataResponses with empty broker list

kafka/conn.py
Fixes #1473 . This change drops the DNS retries that I had originally included. This should return us to the prior behavior where attempting to start a kafka-python client with invalid bootstrap metadata (or a failing DNS system) will raise an exception.
=> Improve connection handling when bootstrap list is invalid

kafka/__init__.py, kafka/consumer/multiprocess.py, kafka/consumer/simple.py, kafka/coordinator/assignors/roundrobin.py, kafka/coordinator/consumer.py, kafka/producer/base.py, kafka/producer/kafka.py, kafka/producer/record_accumulator.py, kafka/protocol/legacy.py, kafka/structs.py, test/test_client_async.py, test/test_conn.py, test/test_coordinator.py, test/test_fetcher.py, test/test_util.py, test/testutil.py
This finishes the split from `kafka.common` to `kafka.errors`/`kafka.structs`.
=> Don't use `kafka.common` internally

kafka/client_async.py, kafka/conn.py, kafka/producer/kafka.py
This PR adds support for on-demand topic metadata fetching. For now, a KafkaClient will fetch metadata for all topics in the initialization. This will have some performance problem when run with a large Kafka cluster.
Adding a `topics` (type `set`) key-value parameter to `KafkaProducer`. This should be all the topics that `send` will be invoked on. For example, if `send` will be invoked on `send('a', ...)` and `send('b', ...)`, then the value for `topics` will be `{'a', 'b'}`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1541)
=> add support for on-demand topic metadata fetch

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py
Fix the related issue #1539
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1542)
=> add kerberos domain name config for gssapi sasl mechanism handshake

kafka/coordinator/consumer.py
The callers of commit_offsets_async seem to imply it should return a future
(eg. future = commit_offsets_async(...)), but it does not. This causes a mismatch
between KafkaConsumer.commit_async()'s documentation and its behaviour.
This fixes that by returning futures that were already available,
we just had to actually return them.
Fixes https://github.com/dpkp/kafka-python/issues/1559
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1560)
=> Return future from commit_offsets_async

kafka/metrics/metrics.py
Without this, the dictionary is not being garbage collected and is leaking memory. After applying this patch, the memory leak I described [here](https://github.com/dpkp/kafka-python/issues/1340#issuecomment-411712947) was fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1569)
=> Clear the metrics dictionary on close (fixes a memory leak).

kafka/errors.py
This error hasn't been thrown since 1.2.4 and I do not see it anywhere else in the library.
https://github.com/dpkp/kafka-python/blob/bc4cc434cddf403a35d0393d68ecfdbfad17c8e5/docs/changelog.rst#124-july-8-2016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1587)
=> Remove ConsumerTimeout

kafka/__init__.py
This solves a warning in linters like PyCharm, which warns that a line like:
```
from kafka import ConsumerRebalanceListener
```
is actually accessing a protected member of a class or module. Adding it to `__all__` should solve this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1591)
=> Expose ConsumerRebalanceListener in __all__

kafka/vendor/six.py
Bump `six` to `1.11.0`. Most changes do not affect us, but it's good to
stay up to date. Also, we will likely start vendoring `enum34` in which
case https://github.com/benjaminp/six/pull/178 is needed.
Note that this preserves the `kafka-python` customization from https://github.com/dpkp/kafka-python/pull/979
which has been submitted upstream as https://github.com/benjaminp/six/pull/176 but not yet merged.
=> Bump vendored `six` to `1.11.0`

benchmarks/consumer_performance.py, benchmarks/producer_performance.py, benchmarks/varint_speed.py, kafka/codec.py, kafka/producer/simple.py, test/fixtures.py, test/test_client.py, test/test_codec.py, test/test_consumer_group.py, test/test_consumer_integration.py, test/test_producer_integration.py, test/test_producer_legacy.py, test/test_protocol.py, test/test_protocol_legacy.py, test/test_util.py
Use vendored `six`, and also `six.moves.range` rather than `xrange`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1605)
=> Vendor `six` consistently

kafka/vendor/enum34.py
This is needed for https://github.com/dpkp/kafka-python/pull/1540.
While the usage there is trivial and could probably be worked around, I'd
rather vendor it so that future code can use enums... since `enum` is
already available in the python 3 stdlib, this will be easy enough to
eventually stop vendoring whenever we finally drop python 2 support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1604)
=> Vendor enum34

pylint.rc
`six.moves` is a dynamically-created namespace that doesn't actually
exist and therefore `pylint` can't statically analyze it.
By default, `pylint` is smart enough to realize that and ignore the
import errors.
However, because we vendor it, the location changes to
`kafka.vendor.six.moves` so `pylint` doesn't realize it should be
ignored.
So this explicitly ignores it.
`pylint` documentation of this feature:
http://pylint.pycqa.org/en/1.9/technical_reference/features.html?highlight=ignored-modules#id34
More background:
* https://github.com/PyCQA/pylint/issues/1640
* https://github.com/PyCQA/pylint/issues/223
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1609)
=> Prevent `pylint` import errors on `six.moves`

docs/Makefile, docs/make.bat
When I was fixing urls the other day, I noticed that sphinx hadn't added
https but there was an open ticket: https://github.com/sphinx-doc/sphinx/issues/5522
Now that that is resolved, I'm updating it here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1610)
=> Fix sphinx url

kafka/__init__.py, kafka/admin/__init__.py, kafka/admin/config_resource.py, kafka/admin/kafka.py, kafka/admin/new_partitions.py, kafka/admin/new_topic.py, kafka/client_async.py, kafka/conn.py, kafka/protocol/__init__.py, test/test_admin.py
Requires cluster version > 0.10.0.0, and uses new wire protocol
classes to do many things via broker connection that previously
needed to be done directly in zookeeper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1540)
=> Add KafkaAdmin class

kafka/record/_crc32c.py, tox.ini
We have many deprecation warnings in the travis logs for things that are fixed in newer versions of `pylint` or `pylint`'s dependencies.
So opening a PR to see if `master` passes on whatever version travis pulls in. Note that `pylint` >= 2.0 does not support python 2, so this will result in different versions of pylint running for python 2 vs python 3. Personally, I am just fine with this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1611)
=> Stop pinning `pylint`

kafka/producer/base.py
I missed this in my previous cleanup back in 9221fcf.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1615)
=> Stop using deprecated log.warn()

docs/tests.rst
Removed some of the hardcoded values as they are now outdated, and just
pointed to where to find the current value in the code.
Also some minor wordsmithing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1613)
=> Minor cleanup of testing doc

test/fixtures.py
This is no longer used anywhere in the codebase
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1617)
=> Remove unused ivy_root variable

test/test_partitioner.py
Minor cleanup in preparation for #1196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1618)
=> Minor aesthetic cleanup of partitioner tests

test/conftest.py, test/test_codec.py, test/test_consumer_group.py, test/test_consumer_integration.py, test/test_failover_integration.py, test/test_producer.py, test/testutil.py
`random_string` now comes from `test.fixtures` and was being
transparently imported via `test.testutil` so this bypasses the
pointless indirect import.
Similarly, `kafka_version` was transparently imported by `test.testutil`
from `test.fixtures`.
Also removed `random_port()` in `test.testutil` because its unused as its been replaced
by the one in `test.fixtures`.
This is part of the pytest migration that was started back in
a1869c4be5f47b4f6433610249aaf29af4ec95e5.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1616)
=> Cleanup fixture imports

kafka/protocol/types.py
PR that pulls in @billyevans suggested performance improvement from #1555:
I noticed that pack/unpack functions from
https://github.com/dpkp/kafka-python/blob/master/kafka/protocol/types.py
might be slightly improved. I made pre-compilation for them. It gives
about 10% better performance compared to the current implementation.
Consumption of 100msg:
```
239884    0.187    0.000    0.287    0.000 types.py:18(_unpack) # new version
239884    0.192    0.000    0.323    0.000 types.py:17(_unpack)
```
I also made some profiling for producers/consumers. It gives about
1-1.5% time savings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1619)
=> Pre-compile pack/unpack function calls

kafka/client_async.py, kafka/coordinator/base.py
This is an attempt to address / fix #1623 and #1626. Major shout out to zhgjun for investigating and suggesting this fix!
Given the thread setup we have right now, I think the easiest way to prevent deadlock is to always acquire the client lock before the coordinator lock. There are still some places in the code that only acquire the coordinator lock. Leaving these in place is dangerous, but I don't think any of them have any possible code path that leads to acquiring the client lock while still holding the coordinator lock.
I've also modified the client poll loop to keep the client lock during callback handling. I don't think this is specifically necessary to fix the deadlock issue reported in the issues above, but I also don't think dropping the client lock before processing callbacks …
=> (Attempt to) Fix deadlock between consumer and heartbeat

kafka/client_async.py, kafka/producer/kafka.py
hi Dana,
we're running kafka-python on a SNS site in china, yesterday we've met an issue about the kafka host hangs because of some kernel gotchas, and the application containers hangs after the kafka, thus the site is down before we restarted the kafka.
after some investigation, we found the writing side of the `wake_w` socketpair is blocking, and with no socket timeout. if the sender thread can not execute `wake_r.receive` but got blocked, `wake_w.sendall(b'x')` would block the `producer.send()` method without timeout. we have a config option about `max_block_ms` which works on ` buffer is full or metadata unavailable`, but have not worked on the `wake_w.send` yet.
we'd prefer the `wake_w.send` method fails fast with a timeout error instead of blocking forever on the producer thread, so …
=> set socket timeout for the wake_w

kafka/producer/record_accumulator.py
Recently, I've spend some human days trying to find where in our multi step pipeline we were having a data loss. It turned out one of our producers were generating batches too often resulting to their expiration. But there were no signs of any problems in logs. This PR attempts to fix this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1553)
=> Verbose logging on messages signalling data loss in producer

test/conftest.py, test/test_consumer.py, test/test_consumer_group.py, test/test_consumer_integration.py, test/test_package.py, test/testutil.py, tox.ini
This migrates tests from `unittest` to `pytest`.
I only migrated tests that will continue to be used even after the
removal of the old `Simple*` classes in #1196.
The motivation for this work was threefold:
1. Reduce the diff size for #1196
2. Continue to familiarize myself with the testing code
3. Improve readability -- `pytest` is generally more readable `unittest`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1620)
=> Migrate from `Unittest` to `pytest`

kafka/admin/kafka.py, kafka/conn.py, kafka/errors.py
`UnsupportedVersionError` is intended to indicate a server-side error:
https://github.com/dpkp/kafka-python/blob/ba7372e44ffa1ee49fb4d5efbd67534393e944db/kafka/errors.py#L375-L378
So we should not be raising it for client-side errors. I realize that
semantically this seems like the appropriate error to raise. However,
this is confusing when debugging... for a real-life example, see
https://github.com/Parsely/pykafka/issues/697. So I strongly feel that
server-side errors should be kept separate from client-side errors,
even if all the client is doing is proactively protecting against
hitting a situation where the broker would return this error.
Fix https://github.com/dpkp/kafka-python/issues/1627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Stop using broker-errors for client-side problems

kafka/admin/kafka.py, kafka/client.py, kafka/client_async.py, kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/consumer/simple.py, kafka/consumer/subscription_state.py, kafka/coordinator/consumer.py, kafka/metrics/metrics.py, kafka/metrics/stats/percentiles.py, kafka/metrics/stats/rate.py, kafka/metrics/stats/sensor.py, kafka/producer/base.py, kafka/producer/future.py, kafka/producer/kafka.py, kafka/producer/keyed.py, kafka/producer/record_accumulator.py, kafka/producer/simple.py, kafka/protocol/legacy.py, kafka/protocol/message.py, kafka/protocol/parser.py, kafka/record/legacy_records.py, test/fixtures.py, test/test_metrics.py, test/test_producer.py, test/testutil.py
Fix #1633
I think I got them all... I would appreciate another pair of eyes to review that I didn't accidentally make mistakes on this.
This is a bit hideous, and definitely overkill, but it's faster than trying to debug `TypeError`s in production...
Alternatively, could switch these to `.format()`. 
Unfortunate that the lovely new python 3.7 syntax f-strings are not backport-able.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1634)
=> Be explicit with tuples for %s formatting

kafka/admin/kafka.py
This is a new class, so let's not support the old version strings and
saddle ourselves with tech debt right from the get-go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1644)
=> Remove support for api versions as strings from KafkaAdmin

kafka/admin/kafka.py
Add group coordinator lookup
We need a way to send a request to the group coordinator.
I spent a day and a half trying to implement a `_send_request_to_group_coordinator()`
that included:
1. caching the value of the group coordinator so that it wouldn't have
to be repeatedly looked up on every call. This is particularly important
because the `list_consumer_groups()`, `list_consumer_group_offsets()`,
and `describe_consumer_groups()` will frequently be used by monitoring
scripts. I know across the production clusters that I support, using a
cached value will save ~1M calls per day.
2. clean and consistent error handling. This is difficult because the
responses are inconsistent about error codes. Some have a top-level
error code, some bury it within the description of the actual item.
3. …
=> Add group coordinator lookup

kafka/admin/kafka.py
The `KafkaAdmin` controller send error handling was completely broken.
It also pinned the metadata version unnecessarily.
Additionally, several of the methods were sending to the controller
but either that was unnecessary, or just plain wrong. So updated
following the pattern of the Java Admin client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1640)
=> Fix KafkaAdmin send to controller

kafka/admin/kafka.py, kafka/structs.py
Add list_consumer_group_offsets() to support fetching the offsets of a consumer group.
Note: As far as I can tell (the Java code is a little inscrutable), the
Java AdminClient doesn't allow specifying the `coordinator_id` or the
`partitions`.
But I decided to include them because they provide a lot of additional
flexibility:
1. allowing users to specify the partitions allows this method to be used even for
older brokers that don't support the OffsetFetchRequest_v2
2. allowing users to specify the coordinator ID gives them a way to
bypass a network round trip. This method will frequently be used for
monitoring, and if you've got 1,000 consumer groups that are being
monitored once a minute, that's ~1.5M requests a day that are
unnecessarily duplicated as the coordinator doesn't change …
=> Add list consumer groups offsets

kafka/admin/kafka.py
Fix list_consumer_groups() to query all brokers
Previously, this only queried the controller. In actuality, the Kafka
protocol requires that the client query all brokers in order to get the
full list of consumer groups.
Note: The Java code (as best I can tell) doesn't allow limiting this to
specific brokers. And on the surface, this makes sense... you typically
don't care about specific brokers.
However, the inverse is true... consumer groups care about knowing their
group coordinator so they don't have to repeatedly query to find it.
In fact, a Kafka broker will only return the groups that it's a
coordinator for. While this is an implementation detail that is not
guaranteed by the upstream broker code, and technically should not be
relied upon, I think it very unlikely to change.
So …
=> Fix list_consumer_groups() to query all brokers

kafka/admin/kafka.py
Set a clear default value for `validate_only` / `include_synonyms`
Previously the kwarg defaulted to `None`, but then sent a `False` so this just makes it more explicit and reduces ambiguity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1645)
=> Set a clear default value for `validate_only` / `include_synonyms`

kafka/admin/kafka.py
Fix describe_groups
This was completely broken previously because it didn't lookup the group
coordinator of the consumer group. Also added basic error
handling/raising.
Note: I added the `group_coordinator_id` as an optional kwarg. As best I
can tell, the Java client doesn't include this and instead looks it up
every time. However, if we add this, it allows the caller the
flexibility to bypass the network round trip of the lookup if for some
reason they already know the `group_coordinator_id`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1642)
=> Fix describe groups

kafka/admin/kafka.py
This is a hodge-podge of changes that crept into my source code while I was working on it. 
I figured I'd put them up under a catch-all commit. Putting this up for now as a PR, but it may be better broken out differently. Also, some of these are trivial style nits that may not be worth fixing.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1647)
=> Various docstring / pep8 / code hygiene cleanups

kafka/admin/kafka.py
Bugfix of something I missed in https://github.com/dpkp/kafka-python/pull/1642
Hat tip to @ulrikjohansson for [noticing this](https://github.com/dpkp/kafka-python/commit/8dab14b6d73d8f1717fdeb46c79807827169fd2d#r31354023).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1650)
=> Bugfix: Always set this_groups_coordinator_id

kafka/consumer/group.py, kafka/producer/kafka.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1682)
=> Bugfix  #1681 - add `.copy()` in metrics() method to avoid thread safety issues

kafka/conn.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1669)
=> Fix SSL connection testing in Python 3.7

test/fixtures.py
Popen objects may deadlock when using stdout=PIPE or stderr=PIPE
with Popen.wait(). Using Popen.communicate() avoids the issue.
I ran into this issue in a fork. This code should behave the same but avoids the possibility of deadlock described here: https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1689)
=> Use Popen.communicate() instead of Popen.wait()

kafka/consumer/fetcher.py, kafka/consumer/group.py
This `skip_double_compressed_messages` flag was added in https://github.com/dpkp/kafka-python/pull/755 in
order to fix https://github.com/dpkp/kafka-python/issues/718.
However, grep'ing through the code, it looks like it this is no longer
used anywhere and doesn't do anything.
So removing it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1677)
=> Remove unused `skip_double_compressed_messages`

kafka/coordinator/base.py
Fixes #1691 and applies fixes based on upstream java client:
(1) rejoin_needed is reset to False in final success callback, not in the JoinResponse callback.
(2) also check that join_future is not pending in ensure_active_group
(3) disable heartbeats during join group
See also: KAFKA-3782, KAFKA-5611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1695)
=> Improve KafkaConsumer group rejoin / disable heartbeats during join group

test/record/test_legacy_records.py
The problem is that the type of required operation result is
"long".
```
>>> type(278251978 & 0xffffffff)
<type 'long'>
```
However, by default "format" method uses __format__():
```
>>> (278251978 & 0xffffffff).__format__('')
'278251978'
```
So, let's compare things using the same engine:
```
>>> "{!r}".format(278251978 & 0xffffffff)
'278251978L'
```
Fixes: https://github.com/dpkp/kafka-python/issues/1717
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1718)
=> Fix test_legacy_correct_metadata_response on x86 arch

docs/requirements.txt
Since 1.3b1 (released Oct 10, 2014) Sphinx has support for NumPy and
Google style docstring support via sphinx.ext.napoleon extension.
The latter is already used, but sphinxcontrib-napoleon requirement
still presents.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1715)
=> Drop dependency on sphinxcontrib-napoleon

kafka/errors.py
According to [kafka docs](https://kafka.apache.org/protocol.html#protocol_error_codes), both are supposed to be retriable errors, so this fix is to resolve that
See issue #1580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1722)
=> Make NotEnoughReplicasError/NotEnoughReplicasAfterAppendError retriable

test/test_consumer_group.py, test/test_consumer_integration.py, test/test_producer.py, test/test_producer_integration.py
Fixes pytest warning:
```
RemovedInPytest4Warning: Fixture "version" called directly.
Fixtures are not meant to be called directly, are created automatically
when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1731)
=> Use test.fixtures.version not test.conftest.version to avoid warnings

kafka/client_async.py
In an effort to reduce the surface area of lock coordination, and thereby hopefully reduce lock contention, I think we can remove locking from the read-only KafkaClient methods: `connected`, `is_disconnected`, `in_flight_request_count`, and `least_loaded_node` . Given that the read data could change after the lock is released but before the caller uses it, the value of acquiring a lock here does not seem high to me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1730)
=> Do not acquire KafkaClient lock for read-only operations

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/coordinator/base.py, test/fixtures.py, test/test_client_async.py
This PR completes #981 and attempts to address several reports of consumer lockups that appear related to KafkaClient blocking for up to the full request_timeout_ms while holding the client lock, while all other threads are prevented from initiating new network requests or connections until the lock is released.
There are 4 commits here. The first is a simple refactor of BrokerConnection that separates queueing of a new network request (via .send / ._send) and performing the actual network IO (via .send_pending_requests).
The second updates KafkaClient to only performing network IO requests during .poll(). It uses the wakeup channel to signal between threads, allowing a sender to wakeup a blocked poller and trigger an immediate call to .send_pending_requests().
The third commit address …
=> Do network connections and writes in KafkaClient.poll()

kafka/conn.py, test/test_conn.py
If we attempt to maintain a FIFO queue of in-flight requests in the BrokerConnection, we will have to be careful that once a request is added to the _protocol buffer that we also make sure to add the response future to the in-flight-requests queue. Furthermore, we need to make sure that the order of requests added to the _protocol buffer is the same order as the order of the IFR queue. Otherwise, if we do not, then we end up with a mismatch between actual response and the expected response as determined by the IFR queue. Currently we do not synchronize the code that does this, so  two requests could come in at the same time and get placed (1) R1 -> _protocol buffer, (2) R2 -> _procotol buffer, (3) R2 -> IFR list, (4) R1 -> IFR list.
To address this issue I've modified BrokerConnection to …
=> Synchronize puts to KafkaConsumer protocol buffer during async sends

kafka/coordinator/consumer.py
Fixes an issue where if commit_offsets_async has to lookup the coordinator before actually sending the offset_commit_request, the request will fail with the following error:
```
Error processing callback
File "/home/runner/pipeline.runfiles/kafka_python_git/kafka/future.py", line 79, in _call_backs
f(value)
TypeError: _do_commit_offsets_async() takes from 2 to 3 positional arguments but 4 were given
```
This is because the current logic directly adds the invocation of _do_commit_offsets_async as a callback to the invocation of lookup_coordinator, but _do_commit_offsets_async has no use for that value, and has no parameter to receive it, resulting in the above error. This PR just passes a wrapper lambda as the actual callback to the invocation of …
=> Ignore lookup_coordinator result in commit_offsets_async

.travis.yml, Makefile, docs/compatibility.rst, setup.py, tox.ini, travis_java_install.sh
Add Python 3.7 to the tests.
Document 3.7 support on PyPi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1614)
=> Add python 3.7 support

kafka/conn.py
This is needed to use kafka-python with python 3.7.
It builds on #1669 and the solution is a slightly modified version of a comment on #1661
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1694)
=> Catch thrown OSError by python 3.7 when creating a connection

kafka/coordinator/base.py
Fixes #1666 . Underlying issue here is a race on consumer.close() between the client, the connections/sockets, and the heartbeat thread. Although the heartbeat thread is signaled to close, we do not block for it. So when we go on to close the client and its underlying connections, if the heartbeat is still doing work it can cause errors/crashes if it attempts to access the now closed objects (selectors and/or sockets, primarily).
This PR adds a blocking thread join to the heartbeat close. This may cause some additional blocking time on consumer.close() while the heartbeat thread finishes. But it should be small in average case and in the worst case will be no longer than the heartbeat_timeout_ms (though if we timeout the join, race errors may still occur).
---
This change is [<img …
=> Attempt to join heartbeat thread during close()

kafka/conn.py
I noticed during local testing that version probing was happening twice when connecting to newer broker versions. This was because we call check_version() once explicitly, and then again implicitly within get_api_versions(). But once we have _api_versions data cached, we can just return it and avoid probing versions a second time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1738)
=> Dont recheck version if api_versions data is already cached

kafka/client_async.py, test/test_client_async.py
This is a small, non-critical fixup that should reduce the forced connection delay when refreshing metadata.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1737)
=> Recheck connecting nodes sooner when refreshing metadata

test/test_conn.py
Small change to avoid doing dns resolution when running local connection tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1739)
=> Mock dns lookups in test_conn

kafka/client_async.py, kafka/conn.py
Very small PR that combines minor changes accumulated in my git stash while working on other issues. Import ordering, an extra comment, and a fix for default protocol parser version (useful during check_version, before we know which actual version to use).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1740)
=> Minor client cleanups

kafka/client_async.py, kafka/cluster.py, test/test_client_async.py
The current client attempts to bootstrap once during initialization, but if it fails there is no second attempt and the client will be inoperable. This can happen, for example, if an entire cluster is down at the time a long-running client starts execution.
This PR attempts to fix this by removing the synchronous bootstrapping from KafkaClient init, and instead merges bootstrap metadata with the cluster metadata. The java client uses a similar approach. This allows us to continue falling back to bootstrap data when necessary throughout the life of a long-running consumer or producer.
Fixes #1670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1736)
=> Retry bootstrapping after backoff when necessary

kafka/consumer/group.py, test/test_consumer.py
`connections_max_idle_ms` must always be larger than `request_timeout_ms`
to avoid potentially unexpected behavior.
Fix #1680.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1688)
=> Error if connections_max_idle_ms not larger than request_timeout_ms

kafka/conn.py
Resolves #1748 based on suggestion by @dpkp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1752)
=> kafka-python #1748 Fix race condition in protocol.send_bytes

test/fixtures.py
This doesn't fully implement SSL fixtures, but as a first step it should help with automatically generating required certificates / keystores / etc. My hope is that this helps generate more community support for SSL testing!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1756)
=> Generate SSL certificates for local testing

kafka/conn.py
Fix for #1741 . Previously we have been wrapping sockets with an SSLContext before connection, and calling `connect_ex` to do a non-blocking connect, then calling `do_handshake`. But the TCP connect itself does not require the SSLContext, and it appears that in general, and definitely on python3.7, non-blocking connect_ex w/ ssl sockets is not fully supported.
So this PR defers wrap_ssl until after the TCP socket is connected, which should side-step all of the ValueError / OSError issues raised by python3.7 due to poor support for connect_ex. Also it is simpler, which I like.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1754)
=> Wrap SSL sockets after connecting

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py
Additional support for #1741 . While testing SSL connections w/ python3.7 locally, I found that the default ssl ciphers that my python3.7 install supported were not sufficient to establish a connection with my kafka broker. This PR adds a new configuration option `ssl_ciphers` that will be passed through to `SSLContext.set_ciphers()` and may allow use of ciphers that are available but not enabled by default on a particular python / openssl installation. In my case, this was `DHE-DSS-AES128-GCM-SHA256` . Without this configuration, my connection attempts failed with ssl.SSLError `UNKNOWN_PROTOCOL`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1755)
=> Allow configuration of SSL Ciphers

kafka/client_async.py, kafka/cluster.py
Fixes #1751 (and part of #1741, related to hostname verification). This PR puts bootstrap metadata into a shadow metadata "cluster", similar to the java client. This moves dns resolution for multi-interface hostnames into BrokerConnection.connect(). And it gives each bootstrap server a unique node-id (rather than all sharing a single node-id of `bootstrap`), which allows the KafkaClient to manage connection attempts more consistently using least-loaded-node, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1753)
=> Maintain shadow cluster metadata for bootstrapping

test/test_conn.py
The time has come to fix these...
```
____________________________ test_connection_delay _____________________________
conn = <kafka.conn.BrokerConnection object at 0x0000000004cc50f8>
def test_connection_delay(conn):
conn.last_attempt = time.time()
>       assert round(conn.connection_delay()) == round(conn.config['reconnect_backoff_ms'])
E       assert 49.0 == 50.0
E        +  where 49.0 = round(49.48000907897949)
E        +    where 49.48000907897949 = <bound method BrokerConnection.connection_delay of <kafka.conn.BrokerConnection object at 0x0000000004cc50f8>>()
E        +      where <bound method BrokerConnection.connection_delay of <kafka.conn.BrokerConnection object at 0x0000000004cc50f8>> = <kafka.conn.BrokerConnection object at 0x0000000004cc50f8>.connection_delay
E        +  and …
```
=> Fix flaky conn tests that use time.time

kafka/admin/client.py, kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/oauth/__init__.py, kafka/oauth/abstract.py, kafka/producer/kafka.py
This PR adds support for OAuthBearer as a method of SASL Authentication as described in [KIP-255](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=75968876) and https://github.com/dpkp/kafka-python/issues/1710.
When initializing the client, the user must pass in an instance of a class that implements a **token** method, which returns an ID or Access Token. The interface is described in the documentation for every class where `sasl_oauth_token_provider` should be configured. I am open to better ideas of where to store the required interface details! 
**Example:**
```python
class TokenProvider(object):
def token(self):
return "some_token_id"
producer = KafkaProducer(
bootstrap_servers='127.0.0.1:9094',
...
security_protocol='SASL_PLAINTEXT', …
```
=> Support SASL OAuthBearer Authentication

kafka/client_async.py, kafka/producer/sender.py
Fix for #1760. the wakeup socketpair is used to signal a different, polling thread that a new request is ready to send on the network. But when the same thread is sending and polling, there is no need for wakeup, and furthermore it is possible that the wakeup itself could block if a large number of sends were processed before polling for responses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1761)
=> Dont do client wakeup when sending from sender thread

kafka/client_async.py
I don't think it is strictly necessary to send before receiving in the poll loop, but I think the design makes more sense. Leveraging the request-time-out loop was more of an optimization to avoid looping through the connection list twice. In the future we might consider other optimizations, including tracking connections w/ pending data to write and using `select` to identify which/when those sockets are available for writing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1762)
=> Send pending requests before waiting for responses

kafka/conn.py, kafka/protocol/parser.py
commit 703f0659 was attempting to fix version detection on 0.8.2 brokers, which have a quirky correlation id response for GroupCoordinator requests when there are no topics created. But setting the BrokerConn api_version to 0.8.2 prematurely inadvertently broke SASL authentication, which checks that the api_version is either unset (None) or >= 0.10 . This PR should fix both issues by also handling the 0.8.2 protocol quirk when the api_version is unset / None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1763)
=> Revert 703f0659 / fix 0.8.2 protocol quick detection

kafka/client_async.py, test/test_client_async.py
This is a simplification of #1765 , intended to address / fix #1760 . The underlying issue here is that if the wakeup socket is full, and so will block on writes, we don't want anything within the poll() method to attempt to write to this socket. This PR updates _maybe_refresh_metadata() to not use wakeups. Because this method is only ever called within poll(), I have made the default wakeup=False. In the future, if the method were invoked from outside / another thread, we would want to pass wakeup=True.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1769)
=> Dont wakeup during maybe_refresh_metadata -- it is only called by poll()

kafka/client_async.py
Since we only call client.check_version() once in the `__init__` of KafkaClient, holding the lock shouldn't be strictly necessary. Nonetheless, I think it makes maintenance a little easier. And in case check_version() is moved out of `__init__`, this should help avoid race conditions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1771)
=> Hold lock during KafkaClient.check_version

kafka/client_async.py
There was a very small possibility that between checking `self._can_send_request(node_id)` and grabbing the connection object via `self._conns[node_id]` that the connection could get closed / recycled / removed from _conns and cause a KeyError. This PR should prevent such a KeyError. In the case where the connection is disconnected by the time we call send(), we should expect conn.send() simply to fail the request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1772)
=> Avoid race condition on client._conns in send()

kafka/client_async.py, test/test_client_async.py
Small change to KafkaClient's state_change_callback to attempt to avoid re-fetching Metadata or increasing bootstrap failure count after an intentional disconnect / conn.close()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1773)
=> Dont treat popped conn.close() as failure in state change callback

kafka/conn.py
Found via StackOverflow -- if user misconfigures BrokerConnection (for example attempts to use gssapi w/o module installed), we raise an exception immediately. But the configuration checks happen before `_sock` is initialized, and the following gc call to `__del__` calls `_close_socket` which crashes on AttributeError. So this is a quick fix for that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1776)
=> Fix possible AttribueError during conn._close_socket

kafka/conn.py
I noticed a call to reset_reconnect_backoff was missing from the connection path for pure SSL (no SASL). Fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1777)
=> Reset reconnect backoff on SSL connection

kafka/conn.py
Minor cleanups. One fixup where we returned early w/o returning the state. Other changes are cosmetic, but I prefer the explicitness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1778)
=> Return explicitly after close in connect()

kafka/conn.py
@isamaru I threw this together as perhaps a middle-ground between the attempts to fix protocol-out-of-sync issues discussed in #1744 .
One small detail re: python atomic operations / locking: my understanding is that a simple boolean check on a python dict is atomic and would not require additional locks. Note the single CALL_FUNCTION opcode:
```
>>> import dis
>>> n = {'a': 1, 'b': 2}
>>> def foo():
...     bool(n)
...
>>> dis.dis(foo)
2           0 LOAD_GLOBAL              0 (bool)
2 LOAD_GLOBAL              1 (n)
4 CALL_FUNCTION            1
6 POP_TOP
8 LOAD_CONST               0 (None)
10 RETURN_VALUE
```
Of course, the value could still change between when the dict is loaded and when it is returned, which means the return value could be stale. But the same is true if we grab the …
=> Additional BrokerConnection locks to synchronize protocol/IFR state

kafka/client_async.py, kafka/conn.py, test/test_client_async.py
Building on #1768 , this PR addresses concurrency issues that may be caused by the BrokerConnection state_change_callback, specifically the callback used by KafkaClient to track connecting nodes and the global socket selector.
To that end, I removed the DISCONNECTING connection state, which should simplify the state model a bit. DISCONNECTING was primarily used to hack around the fact that removing a socket from the client selector must be done before the socket is closed. With this change we'll simply keep the socket open until after the DISCONNECTED callback is completed. But in order to avoid other race conditions, we need to clear the conn._sock attribute before we release the lock. And because the current KafkaClient callback assumes that the socket it needs is conn._sock, I went …
=> Do not call state_change_callback with lock

kafka/coordinator/assignors/range.py
A little Python cleanup:
1. Remove unused variable: `partitions_for_topic`
2. No need to cast to list as `sorted()` already returns a list
3. Using `enumerate()` is cleaner than `range(len())` and handles assigning
`member`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1805)
=> Cleanup python nits in Range Assignor

kafka/admin/client.py
Changes made as per the discussion in #1801 
Uses futures to parallelize broker calls in the admin client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1807)
=> Use futures to parallelize calls to _send_request_to_node()

kafka/consumer/group.py
@jeffwidman wow, this is really embarrassing. I just noticed there's a typo in https://github.com/dpkp/kafka-python/pull/1781, so I corrected it.
It's weird it wasn't caught by any tests -- do we not do any testing for these methods?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1809)
=> Fix typo in _fetch_all_topic_metadata function

kafka/consumer/group.py, kafka/producer/kafka.py, test/fixtures.py, test/testutil.py
The docs for `api_version_auto_timeout_ms` mention setting
`api_version='auto'` but that value has been deprecated for years in
favor of `api_version=None`.
Updating the docs for now, and will remove support for `'auto'` in next
major version bump.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1812)
=> Update docs for api_version_auto_timeout_ms

kafka/producer/kafka.py
This was originally committed to the repo this way, so I'm not sure if it is some kind of obtuse comment or an accidental oversight.
@dpkp any idea why this is here in the source?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1813)
=> Remove unused/weird comment line

kafka/conn.py
Fix for #1817 -- TimeoutError should generally not happen during non-blocking recv, but it is possible and may be more likely when TCP KeepAlive is enabled. This PR treats a TimeoutError the same as a ConnectionError, logging the exception and closing the connection / forcing reconnect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1820)
=> Catch TimeoutError in BrokerConnection send/recv

kafka/client_async.py, test/test_client_async.py
When there are no IFRs, client.poll can potentially block up to the full request timeout ms. For consumers, this would also prevent the heartbeat thread from acquiring the client lock and therefore prevent the heartbeat loop from proceeding. By reducing the poll timeout to the retry timeout (typically 100ms), we should help prevent lock contention and enable the heartbeat thread to loop more freely. Note that when there is an IFR, we may still block for the full request timeout, so this isn't a general solution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1823)
=> Reduce client poll timeout when no IFRs

kafka/client_async.py
Delaying the conversion to seconds makes the code intent more clear.
Originally discussed in https://github.com/dpkp/kafka-python/pull/1823#discussion_r288426474.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1825)
=> Delay converting to seconds

test/test_consumer_group.py
This should hopefully address https://github.com/dpkp/kafka-python/issues/1810. A really simple sanity check for the two methods (I guess it's also a sanity check for `subscribe()` as well)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1829)
=> Sanity test for consumer.topics() and consumer.partitions_for_topic()

kafka/cluster.py, kafka/coordinator/base.py
This changes the coordinator_id to be a unique string, e.g., `coordinator-1`, so that it will get a dedicated connection. This won't eliminate lock contention because the client lock applies to all connections, but it should improve in-flight-request contention.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1822)
=> Use dedicated connection for group coordinator

kafka/admin/client.py
This breaks some of the consumer operations into request generation /
response parsing methods.
The public API does not change. However, this allows power users who are
willing to deal with risk of private methods changing under their feet
to decouple generating the message futures from processing their
responses. In other words, you can use these to fire a bunch of requests
at once and delay processing the responses until all requests are fired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1845)
=> Break consumer operations into request / response methods

kafka/coordinator/consumer.py
Raised once in [https://github.com/dpkp/kafka-python/issues/1594](https://github.com/dpkp/kafka-python/issues/1594)
We're using `api_version=(0, 8, 1)` and `enable_auto_commit=True`. This had worked in `kafka-python==1.3.5` but fails now in `kafka-python==1.4.6`.
In 1.3.5 even though the documentation suggested that commits to ZooKeeper is not supported, we could see the commit reflected upon inspection with zkCli.
In 1.4.6 though, `KafkaConsumer` just doesn't function with the above configuration; because the early exit in `ConsumerCoordinator.poll()` prevents the coordinator from updating `next_auto_commit_deadline`. This stale value, in turn, causes `KafkaConsumer._message_generator()` to preempt the iteration of `self._fetcher` until `consumer_timeout` is reached.
If we allow for …
=> Allow the coordinator to auto-commit for api_version==0.8.1

kafka/admin/client.py
Updated to include SASL_PLAINTEXT and SASL_SSL as options for security_protocol.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1849)
=> Update KafkaAdminClient Docs

kafka/admin/client.py
Previously the `sasl_kerberos_domain_name` was missing from the Admin
client. It is already present in the Consumer/Producer, and in all three
cases gets transparently passed down to the client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1852)
=> Add the `sasl_kerberos_domain_name` arg to `KafkaAdminClient`

kafka/admin/client.py
This splits the FindGroupCoordinator function (which is blocking) into
request generation / response parsing methods.
The public API does not change. However, this allows power users who are
willing to deal with risk of private methods changing under their feet
to decouple generating the message futures from processing their
responses. In other words, you can use these to fire a bunch of requests
at once and delay processing the responses until all requests are fired.
This is modeled on the work done in #1845.
Additionally, I removed the code that tried to leverage the error
checking from `cluster.add_group_coordinator()`. That code had changed
in #1822, removing most of the error checking... so it no longer adds
any value, but instead merely increases complexity and coupling.
---
This …
=> Break FindGroupCoordinator into request/response methods

test/test_conn.py
socket.SOCK_STREAM is platform specific and on some
platforms (most notably on Linux on MIPS) does not
equal 1; so it's better to use the constant where
appropriate.
This change fixes the tests on my MIPS32 LE machine.
Signed-off-by: Ivan A. Melnikov <iv@altlinux.org>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1879)
=> tests: Use socket.SOCK_STREAM in assertions

kafka/conn.py
Resolves #1795.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1883)
=> Load system default CAs when explicit CA not provided

kafka/consumer/group.py
Another PR attempting to address heartbeat timing issues in consumers, especially with the iterator interface. Here we can reduce the client.poll timeout to at most the retry backoff (typically 100ms) so that the consumer iterator interface doesn't block for longer than the heartbeat timeout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1824)
=> Reduce internal client poll timeout for consumer iterator interface

test/conftest.py, test/fixtures.py, test/test_assignors.py, test/test_codec.py, test/test_conn.py, test/test_consumer_group.py, test/test_protocol.py, test/testutil.py
Remove unused import, whitespace, etc. No functional changes, just
cleaning it up so the diffs of later changes are cleaner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1885)
=> Minor test cleanup

test/conftest.py, test/fixtures.py, test/test_client_integration.py, test/test_codec.py, test/test_consumer_group.py, test/test_consumer_integration.py, test/test_failover_integration.py, test/test_producer.py, test/test_producer_integration.py, test/testutil.py
Now that we are using `pytest`, there is no need for a custom decorator
because we can use `pytest.mark.skipif()`.
This makes the code significantly simpler. In particular, dropping the
custom `@kafka_versions()` decorator is necessary because it uses
`func.wraps()` which doesn't play nice with `pytest` fixtures:
- https://github.com/pytest-dev/pytest/issues/677
- https://stackoverflow.com/a/19614807/770425
So this is a pre-requisite to migrating some of those tests to using `pytest` fixtures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1887)
=> Cleanup handling of KAFKA_VERSION env var in tests

.travis.yml, build_integration.sh, servers/0.10.2.2/resources/kafka.properties, servers/0.10.2.2/resources/log4j.properties, servers/0.10.2.2/resources/zookeeper.properties, servers/0.11.0.3/resources/kafka.properties, servers/0.11.0.3/resources/log4j.properties, servers/0.11.0.3/resources/zookeeper.properties
Bump integration tests from Kafka:
- 0.10.2.1 --> 0.10.2.2
- 0.11.0.2 --> 0.11.0.3
The actual resources/config files did not appear to change at all between these minor point releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1890)
=> Bump integration tests to 0.10.2.2 and 0.11.0.3

test/conftest.py, test/test_consumer_group.py, test/test_consumer_integration.py, test/testutil.py
This makes it so the only remaining use of `unittest` is in the old
tests of the deprecated `Simple*` clients. All `KafkaConsumer` tests are
migrated to `pytest`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1886)
=> Convert remaining `KafkaConsumer` tests to `pytest`

kafka/conn.py
This is an extension of #1851 and #1854 -- the underlying issue is that several methods are not handling acquisition and release of the connection lock correctly. I initially tried to address this through more use of `self._lock.release()`, but after sitting on this change for a while I think I agree that we should rely on the `with self._lock:` context manager so that the blocks that are synchronized are more obvious and also are resilient to uncaught exceptions.
I continue to believe that we should use a Lock, not an RLock, and one major reason for that is that the close() method calls back into the KafkaClient state change handler. That handler currently acquires the client lock, and so to avoid deadlocks I think we need to make sure that we no longer hold the connection lock when this …
=> Improve connection lock handling; always use context manager

requirements-dev.txt, tox.ini
requirements-dev.txt: The crc32c version mentioned in this file is 1.5, which fails to compile on non-intel archs. Refer https://github.com/ICRAR/crc32c/issues/6 . It has been fixed since version 1.6.
tox.ini: As mentioned in crc32c github page https://github.com/ICRAR/crc32c , all non-intel architectures have to use the software implementation of it since the hardware its specific to isn't available on non-intel archs. So, to successfully run the test cases, we need to set the environment variable `CRC32C_SW_MODE = auto` .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1904)
=> kafka-python: Fixed crc32c availability on non-intel architectures.

kafka/admin/__init__.py, kafka/admin/acl_resource.py, kafka/admin/client.py, kafka/errors.py, servers/0.10.0.0/resources/kafka.properties, servers/0.10.0.1/resources/kafka.properties, servers/0.10.1.1/resources/kafka.properties, servers/0.10.2.1/resources/kafka.properties, servers/0.11.0.0/resources/kafka.properties, servers/0.11.0.1/resources/kafka.properties, servers/0.11.0.2/resources/kafka.properties, servers/0.9.0.0/resources/kafka.properties, servers/0.9.0.1/resources/kafka.properties, servers/1.0.0/resources/kafka.properties, servers/1.0.1/resources/kafka.properties, servers/1.0.2/resources/kafka.properties, servers/1.1.0/resources/kafka.properties, servers/1.1.1/resources/kafka.properties, servers/2.0.0/resources/kafka.properties, servers/2.0.1/resources/kafka.properties, test/test_admin.py, test/test_admin_integration.py
This is a new attempt at creating user friendly ACL management methods to KafkaAdminClient.
It's building on top of the previous PR (#1646) that only got the protocol stuff merged b.c there were remaining issues to deal with in the api part, and not much time. I think I've covered all the feedback from that PR in this one.
I'm ready for a new round of review, hopefully I can find enough time for fixes and tweaks to land the whole thing  this time =)
Fixes #1638
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1833)
=> Add ACL api to KafkaAdminClient

kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/coordinator/base.py
Now that heartbeats have been moved to a background thread, the pythonic iterator can just wrap `consumer.poll()` and no longer needs to worry about breaking from iteration to support sending background requests. With this approach, some consumers may need to tweak `max_poll_records` and/or `max_poll_interval_ms`, such that consumer's average per-record processing time * max_poll_records < max_poll_interval_ms. Defaults remain at 500 max_poll_records and 5mins for max_poll_interval. This should be sufficient for the vast majority of consumers.
My local testing suggests that this change fixes consumer performance issues reported in #1888 .
Given the reduction in overall complexity, this change may also improve #1672 (though won't completely fix).
Because this is a relatively significant …
=> Wrap consumer.poll() for KafkaConsumer iteration

kafka/client_async.py, kafka/conn.py, kafka/producer/sender.py, test/test_client_async.py, test/test_conn.py
Fix for #1907 - Since we are registering connecting sockets in the selector to wake on EVENT_WRITE, we should not need to set any timeout to handle connecting. This is how the java client works, and makes more sense for kafka-python as we continue to improve the networking model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1909)
=> Rely on socket selector to detect completed connection attempts

kafka/consumer/fetcher.py, test/test_fetcher.py
Attempt to improve wakeup socket issues reported in #1837 #1842
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1911)
=> Do not use wakeup when sending fetch requests from consumer

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, test/test_client_async.py
This PR completes migration of network IO writes to the asynchronous event loop. Each BrokerConnection object maintains a `send_buffer` to capture any bytes returned from KafkaProtocol but not yet placed on the socket buffer via `sock.send` .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1912)
=> Send socket data via non-blocking IO with send buffer

kafka/client_async.py, kafka/coordinator/base.py
Attempt to address heartbeat lock contention by changing the lock acquisition order from client->coordinator to coordinator->client. This aligns with the java client and (I hope) should help improve concurrency coordination between the heartbeat thread loop and the main consumer loop by allowing us to drop the client lock during future processing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1821)
=> Change coordinator lock acquisition order

kafka/consumer/fetcher.py, kafka/coordinator/consumer.py, test/test_fetcher.py
Detailed scenario in #1780 .
The scenario can also trigger another edge case I bumped into while testing which is
`ValueError` exception from `subscription_state.assign_from_subscribed()`
This PR also handles this case by catching the exception and requesting a rejoin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1782)
=> Issue #1780 - Consumer hang indefinitely in fetcher._retrieve_offsets() due to topic deletion while rebalancing 

kafka/consumer/group.py, kafka/producer/kafka.py
Added a function to determine if bootstrap is successfully connected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1876)
=> Added a function to determine if bootstrap is successfully connected

kafka/consumer/fetcher.py, test/test_consumer_integration.py
This should fix lingering master test failures after merging #1782 . Once this lands, we should be ready to release 1.4.7!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1914)
=> Follow up to PR 1782 -- fix tests

.travis.yml, README.rst, docs/compatibility.rst, docs/index.rst, servers/2.1.0/resources/kafka.properties, servers/2.1.0/resources/log4j.properties, servers/2.1.0/resources/zookeeper.properties, servers/2.1.1/resources/kafka.properties, servers/2.1.1/resources/log4j.properties, servers/2.1.1/resources/zookeeper.properties, servers/2.2.0/resources/kafka.properties, servers/2.2.0/resources/log4j.properties, servers/2.2.0/resources/zookeeper.properties, servers/2.2.1/resources/kafka.properties, servers/2.2.1/resources/log4j.properties, servers/2.2.1/resources/zookeeper.properties, servers/2.3.0/resources/kafka.properties, servers/2.3.0/resources/log4j.properties, servers/2.3.0/resources/zookeeper.properties, test/test_consumer_integration.py, test/test_producer_integration.py
kafka-python has been compatible with 2.0+ brokers, but this PR adds the most recent broker version to our travis test matrix and cleans up some legacy tests that still use old SimpleClient / SimpleConsumer / SimpleProducer that don't have full support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1915)
=> Add KAFKA 2.3.0 to test matrix

test/conftest.py, test/fixtures.py, test/test_admin_integration.py
Gets rid of KafkaIntegrationTestCase, removes blocker for #1193 as discussed in #1833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1923)
=> convert test_admin_integration.py to pytest

kafka/admin/client.py, test/test_admin_integration.py
Currently all describe config requests are sent to "least loaded node". Requests for broker configs must, however, be sent to the specific broker, otherwise an error is returned. Only topic requests can be handled by any node.
This changes the logic to send all describe config requests to the specific broker.
Same should be done for alter configs (there is already a comment stating this should be done - I'll be happy to send a PR for this soon'ish).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1869)
=> Fix describe config for multi-broker clusters

kafka/errors.py
This breaks backwards compatibility, probably best not to merge 'til `2.0` release
--
This has been deprecated for a bit in favor of `KafkaConnectionError`
because it conflicts with Python's built-in `ConnectionError`.
Time to remove it as part of cleaning up our old deprecated code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1816)
=> Remove deprecated `ConnectionError`

docs/apidoc/KafkaAdminClient.rst, docs/apidoc/KafkaClient.rst
Since `SimpleClient` was deleted, the new `KafkaClient` currently resides at `kafka.client_async.KafkaClient`... that may get updated in the future, so instead just import the `KafkaClient` from the top-level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1933)
=> Fix doc import paths

kafka/admin/client.py, kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py
See #1945
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1976)
=> Improve docs for reconnect_backoff_max_ms

kafka/admin/client.py, kafka/protocol/admin.py, test/test_api_object_implementation.py
I've been digging in to the admin client and found myself adding extra api version support
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1948)
=> Admin protocol updates

kafka/admin/client.py
**What does this PR do?**
Fixes KafkaAdminClient always returning `IncompatibleBrokerVersion` when passing an `api_version`.
This will calls `check_version()` on init before `get_api_versions()` get called by `_matching_api_version`.
---
Passing an `api_version` to `KafkaAdminClient` seem to always raise `IncompatibleBrokerVersion` line 240
Found that this is because `broker_api_versions = self._client.get_api_versions()` always returns None apparently because `check_version()` had not been called previously.
Per the note from `get_api_versions()`,
> A call to check_version must previously have succeeded and returned
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1953)
=> Fixes KafkaAdminClient returning `IncompatibleBrokerVersion` when passing an `api_version`

kafka/admin/acl_resource.py, test/test_acl_comparisons.py
This allows for direct comparison of ACL objects, and allows us to create `set`s of them
I've found it useful for some work I'm doing to allow us to manage ACLs in some source-controlled way
1) read the 'expected' ACLs from the source controlled file, create ACL objects
2) fetch all 'current' ACLs from kafka
3) create `set` objects of both
4) Do `set` operations to determine what commands I need to run to bring kafka in sync with the expected ACL configurations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1955)
=> Implement __eq__ and __hash__ for ACL objects

kafka/conn.py
Fixes #1963
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1977)
=> Reset conn configs on exception in conn.check_version()

kafka/consumer/group.py
Fixes #1219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1978)
=> Raise AssertionError if consumer closed in poll()

kafka/producer/kafka.py
Fix for #1931 -- python3.7 deadlock in logging producer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1974)
=> Do not block on sender thread join after timeout in producer.close()

kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/consumer/subscription_state.py, kafka/coordinator/consumer.py, test/test_coordinator.py, test/test_fetcher.py
See #1082
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1979)
=> Optionally return OffsetAndMetadata from consumer.committed(tp)

kafka/cluster.py
See #1088
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1980)
=> Do not log topic-specific errors in full metadata fetch

kafka/record/abc.py, kafka/record/default_records.py, kafka/record/legacy_records.py, kafka/record/memory_records.py
Use empty slots for ABC classes, otherwise classes which inherit from them will still have `__dict__`. Also use `__slots__` for more classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1987)
=> Fix slots usage and use more slots

benchmarks/README, benchmarks/record_batch_compose.py, benchmarks/record_batch_read.py, benchmarks/varint_speed.py
I suppose perf is renamed to pyperf now. Update benchmarks to reflect this change.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1986)
=> Fix benchmarks to use pyperf

test/test_coordinator.py
Identity is not the same thing as equality in Python so use ==/!= to compare str, bytes, and int literals. In Python >= 3.8, these instances will raise __SyntaxWarnings__ so it is best to fix them now. https://docs.python.org/3.8/whatsnew/3.8.html#porting-to-python-3-8
% __python__
```
>>> consumer = "cons"
>>> consumer += "umer"
>>> consumer == "consumer"
True
>>> consumer is "consumer"
False
>>> 0 == 0.0
True
>>> 0 is 0.0
False
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1984)
=> Use ==/!= to compare str, bytes, and int literals

kafka/admin/client.py
This is just #1956 but with a clean commit history
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1993)
=> Implement list_topics, describe_topics, and describe_cluster

kafka/admin/client.py
Closes #1994
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1995)
=> Use the controller for topic metadata requests

kafka/admin/client.py
It looks like `AdminClient.describe_topics` is failing because of how we're parsing the response for topic errors: https://github.com/dpkp/kafka-python/blob/bbb8c90391e446de81833bc38dba4233a781fa5b/kafka/admin/client.py#L376-L383
Here's an example of what happens when I run `describe_topics` before the change:
```
$ ./balance-partitions --bootstrap-servers localhost:9092 --topic dummy_topic
=> admin_client = KafkaAdminClient(bootstrap_servers=args.bootstrap_servers)
=> admin_client.describe_topics([args.topic])
File "./balance-partitions", line 16, in <module>
main()
File "~/kafka-tools/lib/commands/balance_partitions.py", line 44, in main
pprint(admin_client.describe_topics([args.topic]))
File "~/kafka-tools/vendor/kafka/admin/client.py", line 521, in …
```
=> Fix topic error parsing in MetadataResponse

kafka/admin/client.py
In KAFKA-8962 the `AdminClient.describe_topics()` call was changed from
using the controller to using the `least_loaded_node()`:
https://github.com/apache/kafka/commit/317089663cc7ff4fdfcba6ee434f455e8ae13acd#diff-6869b8fccf6b098cbcb0676e8ceb26a7R1540
As a result, no metadata request/response processing needs to happen
through the controller, so it's safe to remove the custom
error-checking. Besides, I don't think this error-checking even added
any value because AFAIK no metadata response would return a
`NotControllerError` because the recipient broker wouldn't realize the
metadata request was intended for only the controller.
Originally our admin client was implemented using the least-loaded-node,
then later updated to the controller. So updating it back to
least-loaded node is a simple …
=> KAFKA-8962: Use least_loaded_node() for describe_topics()

kafka/consumer/fetcher.py
This pull request adds a check when consuming messages containing a header whose value is None. In that case, it sets the length to 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2004)
=>  Set length of header value to 0 if None

build_integration.sh
- part 1 of adding zstd compression
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2019)
=> Add 2.1.0 to release list, for testing purposes

kafka/producer/future.py, kafka/producer/record_accumulator.py, kafka/producer/sender.py, kafka/protocol/produce.py, requirements-dev.txt
As mentioned in the commit, these need to come all together, as the future code also implements logic that will unpack depending on version. The other PR would then be the ZSTD code itself
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2020)
=> Add `log_start_offset` to message protocol parsing

docs/conf.py, kafka/client_async.py, kafka/coordinator/base.py, kafka/scram.py
Thanks for this great project!
I wanted to take a few minutes and make a small contribution, so I ran `flake8` over this codebase. A lot of the warnings generated are things that should only be done optionally by maintainers (like formatting and whitespace), but I think I found a few non-controversial changes that would be helpful.
In this PR, I'd like to propose removing a few unused imports and one local variable that is created but never used in `ScramClient`.
Thanks for your time and consideration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2046)
=> remove unused imports

kafka/coordinator/base.py
see issue: https://github.com/dpkp/kafka-python/issues/1985
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2064)
=> Fix #1985: fix consumer deadlock when heartbeat thread request timeout

kafka/structs.py
Document namedtuples in kafka.structs module.
Closes #1874
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2080)
=> Add kafka.structs docstrings

kafka/producer/kafka.py
Logging in an object destructor leads to crashes like the following
```
Exception ignored in: <bound method KafkaProducer.__del__ of 
<kafka.producer.kafka.KafkaProducer object at 0x7f0c47309b38>>
File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 447, in __del__
File "/usr/local/lib/python3.6/site-packages/kafka/producer/kafka.py", line 460, in close
File "/usr/local/lib/python3.6/logging/__init__.py", line 1305, in info
File "/usr/local/lib/python3.6/logging/__init__.py", line 1546, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```
In closing PR #1445, @dpkp made it clear that producers should be closed while they are being destructed.
This commit does not modify the existing …
=> producer/kafka: Disable logging during object destruction

kafka/admin/client.py, kafka/structs.py, test/test_admin_integration.py
First of all thank you for creating and maintaining this kafka client. I utilize it at work for some of the Kafka admin functionalities.
I was trying to utilize the "describe_consumer_groups" function and found that it was returning a raw string output of the response. This is as per the documentation.
The issue that I faced was that the internal member_metadata and member_assignment had still some encoded data.
Eg. output before changes:
```
[(0, u'testgrp', u'Stable', u'consumer', u'range', [(u'consumer-testgrp-1-aff0c665-590e-4921-8b49-034501f0a940', u'consumer-testgrp-1', u'/10.0.0.241', '\x00\x01\x00\x00\x00\x01\x00\x04test\xff\xff\xff\xff\x00\x00\x00\x00', '\x00\x01\x00\x00\x00\x01\x00\x04test\x00\x00\x00\x01\x00\x00\x00\x00\xff\xff\xff\xff')])]
```
Therefore, I am creating this …
=> Enhancement for Kafka Admin Client's "Describe Consumer Group"

kafka/admin/client.py
Currently there's no way to pass timeout to check_version if called from admin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2107)
=> Allow configurable timeouts in admin client check version

kafka/client_async.py
this resolve #2118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2119)
=> Fix initialization order in KafkaClient

kafka/admin/client.py
Small lint cleanup leftover from https://github.com/dpkp/kafka-python/pull/2035
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2126)
=> Lint cleanup

kafka/admin/client.py
Previously there were two methods:
* `_find_coordinator_id()`
* `_find_many_coordinator_ids()`
But they do basically the same thing internally. And we need the plural
two places, but the singular only one place.
So merge them, and change the function signature to take a list of
`group_ids` and return a dict of `group_id: coordinator_id`'s.
As a result of this, the `describe_groups()` command should scale better
because the `_find_coordinator_ids()` command issues all the requests
async, instead of sequentially blocking as the `described_groups()` used
to do.
IIRC, this deviates slightly from the Java client, as they only take a singular group ID... mostly because it gets tricky to handle retriable vs non-retriable errors when you send a bunch at once. However, we don't handle errors quite …
=> Merge _find_coordinator_id methods

kafka/record/util.py, requirements-dev.txt
Fix a deprecation warning in the newest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2128)
=> Fix crc32c deprecation warning

kafka/coordinator/assignors/sticky/sticky_assignor.py
Should solve https://github.com/dpkp/kafka-python/issues/2153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2154)
=> Use six.viewitems instead of six.iteritems to avoid encoding problems

kafka/coordinator/assignors/sticky/sticky_assignor.py, test/test_assignors.py
A follow up for https://github.com/dpkp/kafka-python/pull/2154 with test coverage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2161)
=> Improve sticky assignor's test coverage

kafka/consumer/group.py
Caller may invoke poll with long timeout and then end up closing the
consumer from another thread e.g. to stop the application. Previously
poll forcibly waited for the timeout before existing even though it
could do nothing but spin in busy loop for the remainder of the time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2152)
=> consumer: Exit poll if consumer is closed

README.rst, docs/index.rst, docs/install.rst
Depends on https://github.com/dpkp/kafka-python/pull/2123.
This cleans up the install instructions to specify that optional libs
should be installed using the `kafka-python[opt]` format. This leverages
`setuptools`' `extra_requires` feature to let our users choose to
inherit any versions pins we might apply to our optional dependencies.
This also re-orders the docs slightly to give more visibility to the
`crc32c` install because users are unlikely to realize it exists.
It also cleans up the formatting of the compression libraries slightly,
as they were getting a little unwieldy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2139)
=> Cleanup install instructions for optional libs

setup.py
As noted in https://kafka-python.readthedocs.io/en/master/install.html these are some additional optional libs that we should be specifying in `extras_require` so that callers can specify them if desired.
Fix #2122. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2123)
=> Add the optional compression libs to extras_require

kafka/protocol/types.py
Solution for a TypeError we encountered in release 2.0.2. We migrated from 2.0.1 because of Sticky Assignor support and found the issue (Python 3.8).
```
data = self.consumer.poll(timeout_ms=self.timeout, max_records=max_records)
File "/usr/local/lib/python3.8/dist-packages/kafka/consumer/group.py", line 655, in poll
records = self._poll_once(remaining, max_records, update_offsets=update_offsets)
File "/usr/local/lib/python3.8/dist-packages/kafka/consumer/group.py", line 675, in _poll_once
self._coordinator.poll()
File "/usr/local/lib/python3.8/dist-packages/kafka/coordinator/consumer.py", line 289, in poll
self.ensure_active_group()
File "/usr/local/lib/python3.8/dist-packages/kafka/coordinator/base.py", line 390, in ensure_active_group
future = self._send_join_group_request()
File …
```
=> Hotfix: TypeError: object of type 'dict_itemiterator' has no len()

kafka/admin/client.py, kafka/consumer/group.py, kafka/producer/kafka.py
Provide the consumer, producer and admin client with the option to
create the kafka client from a custom callable, thus allowing more
flexibility in handling certain low level errors
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2144)
=> client: allow injection of custom kafka clients

kafka/protocol/__init__.py, kafka/protocol/admin.py, kafka/protocol/api.py, kafka/protocol/parser.py, kafka/protocol/types.py, test/test_protocol.py
- Add support for varints
- Add support for compact collections (byte array, string, array)
- Add support for new request and response headers, supporting flexible
versions
- Add list of supported flexible versions, plus extraction script
- Add List / Alter partition reassignments apis 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2151)
=> KIP-482: add support for flexible versions / tagged fields

kafka/admin/client.py
Hello!
I have spotted a typo in documentation, and here's the PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2178)
=> fix typo in documentation

kafka/producer/kafka.py
PR for #2200 
This commit fixes typo below: `veriication` -> `verification`.
https://github.com/dpkp/kafka-python/blob/9feeb79140ed10e3a7f2036491fc07573740c231/kafka/producer/kafka.py#L235-L236
Thx to @jeffwidman for providing guidelines for PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2207)
=> Fix typo: veriication -> verification

docs/index.rst
The current link leads to HTTP 404.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2295)
=> Fix the link to the compatibility page

kafka/admin/client.py
The Datadog kafka_consumer check uses the `kafka-python` client library to collect metrics. On very large clusters, it sometimes gets a `KafkaTimeoutError` similar to the one [here](https://github.com/dpkp/kafka-python/issues/2286). We've been able to [work around this](https://github.com/DataDog/integrations-core/pull/13221) by disabling the socket wakeup since our check runs in a single thread (after looking at [this old Github issue](https://github.com/dpkp/kafka-python/pull/1761) that was meant to fix the issue). However, we needed to re-implement some parts of the `_send_request_to_node()` function since the library's version always runs a socket wakeup. 
This PR just adds the `wakeup` argument to `_send_request_to_node()` to make it easier to skip socket wakeup. 
I saw that there's …
=> Allow disabling thread wakeup in send_request_to_node

kafka/codec.py, kafka/coordinator/base.py, kafka/record/abc.py, kafka/record/legacy_records.py
There are small typos in:
- kafka/codec.py
- kafka/coordinator/base.py
- kafka/record/abc.py
- kafka/record/legacy_records.py
Fixes:
- Should read `timestamp` rather than `typestamp`.
- Should read `minimum` rather than `miniumum`.
- Should read `encapsulates` rather than `incapsulates`.
- Should read `callback` rather than `callbak`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2319)
=> docs: Fix a few typos

.github/workflows/python-package.yml
I don't expect this to work yet since I know 3.12 is in an incomplete state, but here goes nothing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2379)
=> Enable testing for Python 3.12 in GH Workflow

kafka/record/_crc32c.py
I'm in the process of building a dynamic analysis tool for python, I ran it on this repo and found a potential improvement.
Right now the builtin crc32 module uses `type(data) != array.array`.
However, using `not isinstance(data, array.array)` has a number of advantages:
- `array.array` subtypes are supported
- follows [PEP-008](https://peps.python.org/pep-0008/#programming-recommendations) recommendations
- better readability
- performance improvement
I measured the performance as follows:
``` bash
$ python3.9 -m timeit -s "from _crc32c import crc_update_faster; import array" -u nsec "crc_update_faster(0, array.array('B', b''))"
500000 loops, best of 5: 576 nsec per loop
$ python3.9 -m timeit -s "from _crc32c import crc_update; import array" -u nsec "crc_update(0, array.array('B', b''))" …
```
=> Use isinstance in builtin crc32

setup.py
Closes https://github.com/dpkp/kafka-python/issues/2350, since it's a valid security concern.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2387)
=> Update setup.py to install zstandard instead of python-zstandard

kafka/vendor/six.py
In this commit, the del X is still commented out due to the fact that upstream https://github.com/benjaminp/six/pull/176 is not merged.
closes #2282
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2398)
=> build: update vendored six from 1.11.0 to 1.16.0

test/test_client_async.py
Hello, Please check my patch. In my environment of Python3.12, an error occurs at the following line. Here is a part of the error message.
```python
>       assert conn.send.called_with(request)
test/test_client_async.py:223: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <MagicMock name='BrokerConnection.send' id='281473155611728'>
name = 'called_with'
def __getattr__(self, name):
if name in {'_mock_methods', '_mock_unsafe'}:
raise AttributeError(name)
elif self._mock_methods is not None:
if name not in self._mock_methods or name in _all_magics:
raise AttributeError("Mock object has no attribute %r" % name)
elif _is_magic(name):
raise AttributeError(name)
if not self._mock_unsafe and (not self._mock_methods or name not in self._mock_methods):
if …
```
=> Uses assert_called_with instead of called_with

.github/workflows/python-package.yml
Let's start testing for 3.13 since it's available in https://github.com/actions/python-versions/blob/main/versions-manifest.json now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2406)
=> Update python-package.yml to expect 3.12 tests to pass and extend experimental tests

kafka/vendor/selectors34.py
it won't import Mapping from collections at python3.11. 
tested it worked from python3.6 to 3.11.2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2394)
=> [FIX] suitablt for the high vresion python.

.github/workflows/python-package.yml
I know that the typical release is uploaded to PyPi manually, however I figure I'd draft a PR with these changes because having the option to start doing this is worthwhile. More info can be found on https://github.com/pypa/gh-action-pypi-publish.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2381)
=> Update python-package.yml to publish to PyPi for every release

.github/workflows/python-package.yml, Makefile, requirements-dev.txt, tox.ini
Move artifact download + installation into Makefile (from build_integration.sh). Call pylint and pytest directly in separate targets. Export KAFKA vars for testing. Add support for running old kafka versions with newer jvm.
=> Refactor Makefile

test/fixtures.py
Pytest fixture cleanup causes a lot of log spam due to closed file descriptors. Small change to avoid logging if handlers are gone.
=> Avoid logging errors during test fixture cleanup

kafka/coordinator/base.py
=> Release coordinator lock before calling maybe_leave_group

test/service.py
We have retry / backoff code in test/fixtures.py, so there's no reason to raise an exception here. Exception causes flakey test runs where backoff/retry would likely have worked. See https://github.com/dpkp/kafka-python/actions/runs/13184905494/job/36804606580
=> Dont raise RuntimeError for dead process in SpawnedService.wait_for()

test/record/test_records.py
Hello, this patch changes the data type of the `expected_size` variable from float to integer. 
The `expected_size` variable could currently be a float when `builder.compression_rate()` returns a float value, but I think it should be an integer because `expected_size` represents the size of a `MemoryRecordsBuilder` object in bytes.
P.S. I got a `test_memory_records_builder` failure on Python-3.13.b02 in Fedora Linux.
https://bugzilla.redhat.com/show_bug.cgi?id=2290344
```
Actual Results:  
=================================== FAILURES ===================================
_______________________ test_memory_records_builder[1-2] _______________________
magic = 1, compression_type = 2
@pytest.mark.parametrize("compression_type", [0, 1, 2, 3])
@pytest.mark.parametrize("magic", [0, 1, 2])
def …
```
=> Fixes the data type of the expected_size variable

servers/0.11.0.0/resources/kafka.properties, servers/0.11.0.1/resources/kafka.properties, servers/0.11.0.2/resources/kafka.properties, servers/0.11.0.3/resources/kafka.properties, servers/1.0.0/resources/kafka.properties, servers/1.0.1/resources/kafka.properties, servers/1.0.2/resources/kafka.properties, servers/1.1.0/resources/kafka.properties, servers/1.1.1/resources/kafka.properties, servers/2.0.0/resources/kafka.properties, servers/2.0.1/resources/kafka.properties, servers/2.1.0/resources/kafka.properties, servers/2.1.1/resources/kafka.properties, servers/2.2.1/resources/kafka.properties, servers/2.3.0/resources/kafka.properties, servers/2.4.0/resources/kafka.properties, servers/2.5.0/resources/kafka.properties, servers/2.6.0/resources/kafka.properties
Conforms `kafka.properties` to distribution `server.properties` for easier maintenance. Adds `group.initial.rebalance.delay.ms=0` to improve test speed.
=> Update kafka properties template; disable group rebalance delay

kafka/conn.py
=> Handle socket init errors, e.g., when IPv6 is disabled

kafka/conn.py
=> Check for socket and unresolved futures before creating selector in conn.check_version

kafka/admin/client.py, kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py, kafka/producer/sender.py, test/conftest.py, test/test_client_async.py, test/test_conn.py
The primary goal of this PR is to reduce busy-polling during broker and network failures. Several incremental changes are included:
* Merge BrokerConnection blacked_out() and connection_delay() logic and eliminate delays / blackouts when cycling through entries from a single dns lookup.
* Improve request-timeout handling in client.poll() by checking all connections for the next potential in-flight-request timeout.
* Drop 100ms timeout override when there are no in-flight requests (added prior to full async connection support)
* Do not mark connection as sending if future immediately resolves (error).
* Remove flat 100ms timeout for unfinished futures (added prior to full async connection support)
* Respect connection delays during metadata refresh when all brokers are unavailable.
* Honor …
=> Improve client networking backoff / retry

kafka/cluster.py, kafka/errors.py
To improve debugging against newer brokers. See #2306
=> Retain unrecognized broker response error codes with dynamic error class

kafka/client_async.py
Attempt to be a bit more defensive with wakeup socketpair. Check for socket error and rebuild socketpair if necessary. Use a `_waking` flag to avoid writing more bytes to the socketpair when it's not needed. Raise errors on failed write attempts.
=> Check for wakeup socket errors on read and close and reinit to reset

kafka/codec.py, test/test_codec.py
=> Do not validate snappy xerial header version and compat fields

Makefile, servers/resources/default/kafka.properties, servers/resources/default/kafka_server_jaas.conf, servers/resources/default/log4j.properties, servers/resources/default/zookeeper.properties, test/fixtures.py
This should make it easier to test new versions.  Also I've updated the authorizer class name, which changed in 2.4+
=> Add default resources for new kafka server fixtures

kafka/admin/client.py
Added missing doc strings for the following methods:
_convert_new_topic_request
list_topics
describe_topics
describe_cluster
_convert_describe_acls_response_to_acls
_convert_create_acls_resource_request_v0
_convert_create_acls_resource_request_v1
_convert_create_acls_response_to_acls
_convert_delete_acls_resource_request_v0
_convert_delete_acls_resource_request_v1
_convert_delete_acls_response_to_matching_acls
_convert_describe_config_resource_request
_convert_alter_config_resource_request
_convert_create_partitions_request
_convert_delete_groups_response
_delete_consumer_groups_send_request
_wait_for_futures
=> Added missing docstrings in admin/client.py

kafka/admin/client.py, kafka/client_async.py, kafka/conn.py, kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/producer/kafka.py, kafka/producer/sender.py, kafka/protocol/admin.py, kafka/protocol/metadata.py, test/test_coordinator.py, test/test_fetcher.py, test/test_sender.py
Adapts `_matching_api_version` from admin client, adding an optional `max_version` kwarg to avoid breaking code if/when new protocol definitions are added without full code support. Use `client.api_version(operation, max_version=x)` to select api versions in consumer/producer/client code.
=> Add KafkaClient.api_version(operation) for best available from api_versions

kafka/consumer/fetcher.py, kafka/record/default_records.py, test/record/test_records.py
=> Decode and skip transactional control records in consumer

kafka/coordinator/base.py, kafka/protocol/group.py
Minor updates to JoinGroup/SyncGroup/LeaveGroup/Heartbeat to support throttle_time_ms field.
=> Support 2.1 baseline consumer group apis

kafka/client_async.py, test/test_client_async.py
Avoid assertion error if broker metadata is not found
=> Improve error handling in client._maybe_connect

kafka/client_async.py, test/test_client_async.py
Renames `_maybe_connect` -> `_init_connect` and only attempts to progress connection state if connection is currently disconnected. This moves all secondary connection work into the selector / poll loop. Maybe refresh metadata now runs after the connecting loop, calls `_init_connect` directly, and returns a retry timeout if connection fails immediately. This should help fix a race condition where a quick failing connection caused us to block indefinitely in the poll selector.
=> Client connection / maybe_refresh_metadata changes

kafka/client_async.py, kafka/cluster.py, kafka/conn.py, kafka/consumer/fetcher.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/producer/sender.py, test/test_conn.py
=> Implement client-side connection throttling / KIP-219

kafka/admin/client.py, kafka/cluster.py, kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/consumer/subscription_state.py, kafka/coordinator/consumer.py, kafka/errors.py, kafka/protocol/list_offsets.py, kafka/protocol/offset_for_leader_epoch.py, kafka/record/default_records.py, kafka/structs.py, test/test_consumer_integration.py, test/test_coordinator.py, test/test_fetcher.py
Adds leader_epoch fields to `OffsetAndMetadata` and `OffsetAndTimestamp` structs. Adds `cluster.leader_epoch_for_partiiton(tp)` for future use. For now all apis use -1 as leader_epoch. This should be ok for 2.1 baseline, but need to implement full leader_epoch support before bumping to FetchRequest v11 (v2.3).
Note that FetchRequest v10 also enables zstd compression.
=> Add baseline leader_epoch support for ListOffsets v4 / FetchRequest v10

kafka/client_async.py, kafka/conn.py, kafka/protocol/api_versions.py, test/test_conn.py
Moves ApiVersionsRequest into pre-connection state handling, prior to SaslHandshake. Use v2 for initial request and check for UnsupportedVersionError.
Skips ApiVersionsRequest if `api_version` has been configured by user.
=> Call ApiVersionsRequest during connection, prior to Sasl Handshake

kafka/admin/client.py, kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py, kafka/sasl/gssapi.py, kafka/sasl/oauth.py, kafka/sasl/plain.py, kafka/sasl/scram.py
`sasl_kerberos_name` may be useful to override the internal gssapi.Name construction using hostbased canonicalized name.
=> Cleanup sasl mechanism configuration checks; fix gssapi bugs; add sasl_kerberos_name config

pyproject.toml, requirements-dev.txt, test/record/test_default_records.py, test/record/test_legacy_records.py, test/test_conn.py, test/test_consumer_integration.py
"mock" is included inside the standard "unittest" package in Python >= 3.3.
(This is an alternatve version of what was proposed (and declined) earlier in #2516. The idea is to allow distributions to package kafka-python without having to patch it explicitly to remove the "mock" dependency).
=> Make the "mock" dependency optional (only used in Python 2.7).

kafka/client_async.py, kafka/conn.py, kafka/consumer/fetcher.py, kafka/coordinator/assignors/sticky/sticky_assignor.py, kafka/coordinator/consumer.py, kafka/metrics/metric_name.py, kafka/metrics/quota.py, kafka/producer/kafka.py, kafka/protocol/api_versions.py, kafka/protocol/commit.py, kafka/protocol/find_coordinator.py, kafka/protocol/offset_for_leader_epoch.py, kafka/protocol/sasl_authenticate.py, kafka/sasl/gssapi.py, test/test_admin.py, test/test_admin_integration.py, test/test_cluster.py, test/test_fetcher.py, test/test_object_conversion.py, test/test_protocol.py, test/test_sender.py
`ruff check --exclude kafka/vendor/ kafka/ test/`
=> Fix lint issues via ruff check

kafka/conn.py, kafka/sasl/__init__.py, kafka/sasl/abc.py, kafka/sasl/gssapi.py, kafka/sasl/oauth.py, kafka/sasl/plain.py, kafka/sasl/scram.py, kafka/sasl/sspi.py
Update to @manuco PR #2219 for new sasl module framework
=> feat: Add SSPI (Kerberos for Windows) authentication mechanism

kafka/producer/kafka.py
=> Attempt to fix metadata race condition when partitioning in producer.send

kafka/consumer/group.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py
Should prevent blocking consumer beyond timeout when cluster is down.
Fix: #1322, #1804, #2059
=> Timeout coordinator poll / ensure_coordinator_ready / ensure_active_group

kafka/coordinator/base.py
Disconnected doesn't always mean we can't make immediate progress. Aligns with java client.
=> Only mark coordinator dead if connection_delay > 0

kafka/client_async.py, kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/util.py, test/fixtures.py, test/test_client_async.py, test/test_consumer_group.py
Also check for coordinator.poll failure, and fix `needs_rejoin() on timeout and eventual success.
=> Support client.poll with future and timeout_ms

kafka/coordinator/base.py
See https://issues.apache.org/jira/browse/KAFKA-4160 . The original fix was intended to support rebalance listeners that may run longer than the session timeout.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1438)
=> KAFKA-4160: Ensure rebalance listener not called with coordinator lock

test/conftest.py, test/fixtures.py, test/service.py
To test with a pre-configured kafka broker:
```
ZOOKEEPER_URI="zk://127.0.0.1:50553" KAFKA_URI="kafka://127.0.0.1:50557" make test
```
(local broker fixture available via `KAFKA_VERSION=3.9.0 python -m test.fixtures kafka` for example)
=> Fix testing with external fixtures

kafka/admin/client.py, kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py, kafka/socks5_wrapper.py
Implement support for SOCKS5 proxies. Implement a new proxy wrapper that handles SOCKS5 connection, authentication and requesting connections to the actual Kafka broker endpoints.
The proxy can be configured via a new keyword argument `socks5_proxy` to consumers, producers or admin client. The value is URL with optional username and password. E.g.
`socks5://user:secret@proxy.example.com:10800`
The implementation is done in state machine that makes progress on repeated calls to connect_ex. The rationale with this bit strange design is to minimize amount of changes on the actual BrokerConnection object.
(rebase of #2169)
=> Support connections through SOCKS5 proxies

kafka/client_async.py, kafka/conn.py
When a single hostname returns multiple dns records, wait until we try and fail connecting to all of the available records before refreshing metadata.
=> Only refresh metadata if connection fails all dns records

kafka/client_async.py
=> Fix OverflowError when connection_max_idle_ms is 0 or inf

kafka/coordinator/base.py
Prefer to avoid sending FindCoordinatorRequest over bootstrap connection.
=> Delay group coordinator until after bootstrap

kafka/consumer/fetcher.py
=> Log warning when attempting to list offsets for unknown topic/partition

kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/util.py, test/test_fetcher.py
Should help avoid unexpected blocking in consumers.
Fix #1346
=> Add optional timeout_ms kwarg to remaining consumer/coordinator methods

kafka/coordinator/consumer.py
=> Call default_offset_commit_callback after _maybe_auto_commit_offsets_async

kafka/future.py
=> Add lock synchronization to Future success/failure

kafka/conn.py, test/test_conn.py
=> Improve connection error handling when try_api_versions_check fails all attempts

pyproject.toml
Without this, we get this in the Fedora package when trying to upgrade to 2.1.0:
```
+ /usr/bin/pytest --ignore=test/test_consumer_integration.py --ignore=test/record/test_util.py test
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --timeout=300
inifile: /builddir/build/BUILD/python-kafka-2.1.0-build/kafka-python-2.1.0/pytest.ini
rootdir: /builddir/build/BUILD/python-kafka-2.1.0-build/kafka-python-2.1.0
```
Fedora update pull request submitted here: https://src.fedoraproject.org/rpms/python-kafka/pull-request/5
=> Fix packaging of 2.1.0 in Fedora: testing requires "pytest-timeout".

kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/consumer/subscription_state.py, kafka/record/abc.py, kafka/record/default_records.py, kafka/record/legacy_records.py, kafka/record/memory_records.py, test/test_fetcher.py
(Lots of commits here, planning to split some into separate PRs).
After more closely reviewing fetch_offset code, namely changes from #1724, it looks like there may be edge cases where offset tracking "loses" messages. #2011 highlights this for paused partitions, but I believe the same issue could happen when using the `consumer.poll()` interface and experiencing a rebalance or other event that causes current fetch response data to become "unfetchable". In that case the fetch response will be discarded without returning records, but the subscription position will still be updated to the end of the fetch response! This would cause the discarded records to be "lost" to the consumer without raising an exception or logging any useful message (the prior log message was at level 0, which is …
=> Lazy unpack records in Consumer Fetcher

kafka/cluster.py, kafka/consumer/group.py, kafka/coordinator/consumer.py
=> Return empty set from consumer.partitions_for_topic when topic not found

kafka/client_async.py, kafka/consumer/subscription_state.py, kafka/producer/kafka.py, kafka/util.py, test/test_util.py
=> Move ensure_valid_topic_name to kafka.util; use in client and producer

kafka/consumer/fetcher.py, kafka/consumer/subscription_state.py, test/test_fetcher.py
=> KIP-74: Manage assigned partition order in consumer

kafka/consumer/subscription_state.py, test/test_consumer_integration.py, test/test_coordinator.py
=> Use SubscriptionType to track topics/pattern/user assignment

kafka/conn.py
=> Reset SASL state on disconnect

kafka/client_async.py, kafka/conn.py
Intended to align connection state with log messages, so update state first + log state change second.
This moves state change to CONNECTING prior to sock initialization, which means that `close()` can now be called without a sock, and that means that the sock passed to `state_change_callback` can be None, though only when disconnected.
=> Improve connection state logging

kafka/consumer/fetcher.py, test/test_fetcher.py
Checking client.ready(node_id) after generating fetch requests can cause incremental fetch session to get out of sync. Do basic checks before creating fetch sessions, then let the callback handlers handle errors and reset fetch session if necessary.
Fix #2575
=> Dont block pending FetchRequests when Metadata update requested

kafka/consumer/group.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py
Changes some existing AssertionErrors to UnsupportedVersionError, and version checks to guard `ensure_active_group`, `join_group`, `maybe_leave_group` (and `_start_heartbeat_thread`)
=> Raise UnsupportedVersionError from coordinator

kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/producer/kafka.py, kafka/producer/record_accumulator.py, kafka/producer/sender.py, test/conftest.py, test/test_coordinator.py, test/test_fetcher.py, test/test_sender.py
=> Pass metrics_enabled=False to disable metrics

kafka/metrics/compound_stat.py, kafka/metrics/kafka_metric.py, kafka/metrics/metric_config.py, kafka/metrics/metric_name.py, kafka/metrics/quota.py, kafka/metrics/stats/avg.py, kafka/metrics/stats/count.py, kafka/metrics/stats/histogram.py, kafka/metrics/stats/max_stat.py, kafka/metrics/stats/min_stat.py, kafka/metrics/stats/percentile.py, kafka/metrics/stats/percentiles.py, kafka/metrics/stats/rate.py, kafka/metrics/stats/sampled_stat.py, kafka/metrics/stats/sensor.py, kafka/metrics/stats/total.py
=> Use __slots__ for metrics

kafka/client_async.py, kafka/producer/kafka.py, kafka/producer/record_accumulator.py, kafka/producer/sender.py, kafka/producer/transaction_state.py, kafka/protocol/init_producer_id.py, kafka/record/default_records.py, kafka/record/memory_records.py, test/test_producer.py, test/test_record_accumulator.py, test/test_sender.py
#1396
"Idempotence" here means that the KafkaProducer avoids causing duplicate messages on the broker via retries by using a combination of producer_id and sequence numbers.
=> KIP-98: Add idempotent producer support

kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/consumer/subscription_state.py, kafka/protocol/fetch.py, kafka/record/abc.py, kafka/record/default_records.py, kafka/record/legacy_records.py, test/test_fetcher.py
=> KIP-98: Add Consumer support for READ_COMMITTED

test/sasl/test_msk.py
This PR fixes the `datetime` deprecation warnings that can be viewed in the [CI logs](https://github.com/dpkp/kafka-python/actions/runs/14481536471/job/40619297397#step:10:81):
```
test/sasl/test_msk.py::test_aws_msk_iam_client_temporary_credentials
/home/runner/work/kafka-python/kafka-python/test/sasl/test_msk.py:13: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
now = datetime.datetime.utcfromtimestamp(1629321911)
```
=> Resolve datetime deprecation warnings

kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/consumer/subscription_state.py, test/test_fetcher.py
* KAFKA-5078 - Defer fetch record exception if iterator has already moved across a valid record
* KAFKA-5075 - Defer consumer fetcher exception if fetch position has already increased
* KAFKA-4937 - Batch offset fetches in the Consumer
* KAFKA-4547 - Avoid resetting paused partitions to committed offsets
=> Consumer improvements

kafka/producer/future.py, kafka/producer/kafka.py, kafka/producer/record_accumulator.py, kafka/producer/sender.py, kafka/record/default_records.py, kafka/record/memory_records.py, test/record/test_default_records.py, test/test_record_accumulator.py, test/test_sender.py
Default is 2mins (120000ms). Also update default `retries` to infinite.
Fix #1723
=> KIP-91: KafkaProducer delivery_timeout_ms

kafka/consumer/group.py
fixing error `AttributeError: 'SubscriptionState' object has no attribute 'need_offset_reset'. Did you mean: 'request_offset_reset'?`
=> Fix SubscriptionState AttributeError in KafkaConsumer

kafka/consumer/fetcher.py, test/test_fetcher.py
The `client.ready(node_id)` check was removed in 2.1 but needs to remain until we implement send queues for connecting nodes.
Fix #2604
=> Only create fetch requests for ready nodes

kafka/cluster.py, kafka/conn.py, test/test_cluster.py, test/test_conn.py
=> Ignore leading SECURITY_PROTOCOL:// in bootstrap_servers

kafka/coordinator/consumer.py, kafka/errors.py
=> Do not reset_generation after RebalanceInProgressError; improve CommitFailed error messages

kafka/producer/record_accumulator.py, kafka/producer/sender.py, test/test_sender.py
=> Fix producer busy loop with no pending batches

kafka/coordinator/base.py
In #1438 we added logic to disable the heartbeat thread while processing group rebalances. Heartbeats are then reenabled via a callback on the final join group success future, which is triggered after the final syncgroup request succeeds and the member assignment data is received.
However, there is a race condition: (1) if the `join_group()` call times out while the join/sync requests are in flight, (2) the join/sync future succeeds after the timeout while the consumer is not calling `join_goup()`, (3) the future enables the heartbeat thread, (4) the next call to `join_group()` disables the heartbeat thread before finding that the future has succeeded. In this case the consumer will be in a stable group membership but will not send any heartbeat requests.
The fix here is to only disable …
=> Only disable heartbeat thread once at beginning of join-group

kafka/coordinator/base.py, kafka/coordinator/heartbeat.py
I noticed that we dont log the heartbeat configuration anywhere, so adding to help with debugging.
Also updating config checks to warn if heartbeat is above recommended 1/3rd of session timeout.
Biggest change is to catch all `Exception` in heartbeat thread run loop. RuntimeError may have been too limiting, and if we fail to catch an exception that stops the thread without setting `self.failed` then we will never restart the heartbeat thread and will not be able to send any additional heartbeats -- and worse the error does not get logged and the user is not alerted.
=> Minor Heartbeat updates: catch more exceptions / log configuration / raise KafkaConfigurationError

kafka/coordinator/base.py, test/integration/test_consumer_group.py
Both `lookup_coordinator` and `_send_heartbeat_request` make client api calls that require locking. The tricky part of the heartbeat run loop is that we need to always acquire client lock first and coordinator lock second (to avoid deadlocks), but we also cannot hold the client lock while calling coordinator lock.wait() . To make this easier, switch from context managers to try / finally and catch any RuntimeError if the client lock has already been released when we reach the finally block.
=> Acquire client lock in heartbeat thread before sending requests

kafka/coordinator/base.py, test/test_coordinator.py
Slight change to heartbeat thread loop: if coordinator is not yet connected, short circuit so we can continue with `client.poll()`. When coordinator is connected we can log the time to next heartbeat and wait (dropping the prior backoff_retry_ms loop). We'll rely on `lock.notify()` if there is a failure or other change that would impact heartbeating.
=> Wait for next heartbeat in thread loop; check for connected coordinator

kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/errors.py
Also do not pause offset commits during metadata update.
=> Update offset commit error handling; use RebalanceInProgressError if applicable

kafka/coordinator/base.py
* add requests/responses to debug logs
* log member-id from initial join group
* add heartbeat success/failure logs
* log join group success immediately (before sync group)
* log all join group response errors as info or higher
=> More coordinator / heartbeat logging

kafka/producer/kafka.py
=> Fix timeout seconds error message in KafkaProducer

kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/coordinator/consumer.py
Possible fix for #2628 - if the attempt to fetch committed offsets times out or otherwise fails (potentially throttled or too-many-in-flight requests) then we were resetting offsets using offset_reset_policy. We should only apply reset policy after offset commits have been fetched (only partitions w/o committed offsets should be reset).
=> Do not reset fetch positions if offset commit fetch times out

kafka/sasl/gssapi.py, test/sasl/test_gssapi.py
=> Fix sasl gssapi plugin: do not rely on client_ctx.complete in auth_bytes()

kafka/conn.py, test/test_conn.py
=> Set the current host in the SASL configs

kafka/consumer/subscription_state.py, kafka/util.py
=> Add synchronized decorator; add lock to subscription state

kafka/sasl/msk.py, test/sasl/test_msk.py
Fix typo and add a test. Also log the scope of the generated token for debugging.
=> Fix decoding bug in AWS_MSK_IAM mechanism

kafka/cluster.py, kafka/producer/kafka.py, test/test_cluster.py
Improve behavior when single topic is unauthorized.
=> Do not ignore metadata response for single topic with error

kafka/admin/client.py
=> Use client.await_ready() to simplify blocking wait and add timeout to admin client

kafka/coordinator/base.py
Fixes heartbeat thread clean shutdown during `close()`. Were holding `coordinator._lock` in outer function so that inner `notify()` did not actually unblock heartbeat thread.
=> Fix coordinator lock contention during close()

kafka/admin/client.py, kafka/consumer/group.py, kafka/coordinator/assignors/abstract.py, kafka/coordinator/assignors/range.py, kafka/coordinator/assignors/roundrobin.py, kafka/coordinator/assignors/sticky/sticky_assignor.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/coordinator/protocol.py, kafka/coordinator/subscription.py, kafka/protocol/commit.py, kafka/protocol/group.py, test/integration/test_admin_integration.py, test/test_assignors.py, test/test_coordinator.py
Implements static consumer group membership from KIP-345. Pass `group_instance_id` to KafkaConsumer() to specify static group membership. Raises `FencedInstanceIdError` on duplicate consumers if id is reused (in practice the older consumer is typically the one that raises the error). Partition assignors have been updated to consider static members, aligning with the java client implementations.
Note that there are some internal / non-public interface changes that may break code if it has tight dependencies.
=> KIP-345 Consumer group static membership

kafka/admin/client.py, kafka/protocol/struct.py, test/test_object_conversion.py
Should help with migration to __slots__
=> Switch protocol code to getattr/setattr from __dict__

kafka/consumer/fetcher.py, kafka/sasl/gssapi.py
2.3 will likely be the last feature release that supports python2. Planning to backport these fixes to 2.2.x.
Ran test suite locally w/ python2 to validate.
=> python2 fixups

kafka/admin/acl_resource.py, kafka/admin/client.py, kafka/client_async.py, kafka/cluster.py, kafka/protocol/admin.py, kafka/protocol/metadata.py, kafka/protocol/types.py, kafka/util.py, test/test_protocol.py, test/test_util.py
Mostly a change to admin client responses, but also updates consumer/producer to use Metadata request v8. Adds `BitField` type that is not currently defined by kafka protocol spec but is implied.
=> KIP-430: Return Authorized Operations in Describe Responses

kafka/consumer/fetcher.py
Mostly bumping api version; LeaderNotAvailableError / OffsetNotAvailableError were already handled by fallback; now they will be checked and logged as debug level instead of warning.
=> KIP-207: Add ListOffsetsRequest v5 / handle OffsetNotAvailableError

kafka/consumer/group.py
I saw this this morning while at work and thought I should contribute this fix to such a monumental and amazing project, as we jokingly expressed earlier in today's meeting.
=> docs: Fix slight spelling mistake

kafka/producer/record_accumulator.py, kafka/producer/transaction_manager.py
Call site
https://github.com/dpkp/kafka-python/blob/2abf2cd6458dcb069940c04da2711aa41683f4f4/kafka/producer/sender.py#L285
This is called in Sender._maybe_send_transactional_request(), but over there it's called without `_` prefix. Since this method is accessed by other classes I assume we should remove the prefix, instead of making the caller call `_flush_in_progress` instead
=> fix flush_in_progress not visible to sender
