dpkp/kafka-python

.travis.yml
You will need to enable the repo at http://coveralls.io/ as well
You can see how it looks here:
https://coveralls.io/builds/1800568
=> This enables coveralls with travis

docs/usage.rst, kafka/producer/base.py, kafka/producer/keyed.py, kafka/producer/simple.py, test/test_producer.py, test/test_producer_integration.py
This re-enables test_switch_leader_async and w/ patches should now pass.
=> Fixups for PR 331 (async producer)

kafka/consumer/simple.py, test/test_consumer.py
Tests and fix for remaining bug in #386
=> Simple consumer leader change

kafka/producer/base.py, test/test_producer.py
This fixes (and tests) async producer on python3.
=> Async producer responses

test/service.py, test/test_conn.py, test/test_consumer_integration.py, test/test_failover_integration.py, test/testutil.py, tox.ini
Included are some small updates to make tests a bit faster and reduce some logging noise when there are failures.
=> Test logging

kafka/producer/base.py, test/test_producer.py
=> Sync producer fail on error kwarg

kafka/consumer/simple.py, kafka/producer/base.py
Add stringified error-types to consumer and producer error logs
=> Log error type

test/test_client_integration.py, test/test_consumer_integration.py, test/test_failover_integration.py, test/test_producer_integration.py, test/testutil.py
We'll need more powerful test filtering to support new server versions and new apis.
=> Refactor kafka_versions to support arbitrary operators (> >= < <= ! =)

kafka/producer/simple.py, test/test_producer.py, test/test_producer_integration.py
=> Handle new topic auto-creation in SimpleProducer.send_messages

kafka/client_async.py, test/test_client_async.py
=> Refresh metadata on failed connection attempts

kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/consumer/subscription_state.py, kafka/coordinator/consumer.py
see https://issues.apache.org/jira/browse/KAFKA-2978
=> KAFKA-2978: consumer stops fetching when positions get out of sync

kafka/client_async.py, kafka/consumer/group.py
=> Prevent idle CPU spin by sleeping if there are no sockets to read

kafka/client_async.py, kafka/consumer/fetcher.py, kafka/consumer/group.py
Fix #497 and #498 - check assignment inside iterator yield loop, and improve init_fetches() pipelining
=> Improve iterator fetch requests

docs/apidoc/KafkaClient.rst, kafka/__init__.py, kafka/client.py, kafka/conn.py, kafka/consumer/base.py, kafka/consumer/multiprocess.py, kafka/consumer/simple.py, test/test_package.py
=> Add DeprecationWarnings to legacy classes

kafka/consumer/group.py, kafka/coordinator/consumer.py, test/test_producer.py
=> Support group_id=None to disable offset commits and group membership

kafka/__init__.py
=> Add logging NullHandler to avoid No Handlers warnings

kafka/consumer/group.py
=> Fix internal timeout / sleep handling in consumer iterator

kafka/consumer/group.py, kafka/coordinator/assignors/range.py, kafka/coordinator/assignors/roundrobin.py, kafka/coordinator/consumer.py, kafka/coordinator/protocol.py, test/test_assignors.py, test/test_coordinator.py
=> Add RangePartitionAssignor (and use as default)

kafka/producer/buffer.py, kafka/producer/record_accumulator.py
=> Support batch_size = 0 in producer buffers

docs/index.rst
`json.loads()` is for deserialising.
=> Fix `value_serializer` parameter in example

kafka/producer/kafka.py, kafka/producer/sender.py
Super simple produce loop with default configs shows ~20% throughput increase. 13.9K -> 16.8K msg/sec.
=> Producer optimization

.travis.yml
https://github.com/travis-ci/travis-ci/issues/1675 is now closed,
but I don't know of a good way to test this.
=> Only deploy master branch now that travis bug is fixed.

kafka/consumer/group.py, kafka/consumer/subscription_state.py, test/test_consumer_group.py
=> KAFKA-2698: add paused API

build_integration.sh, kafka/client_async.py, kafka/conn.py, kafka/socketpair.py, test/test_consumer.py
Attempt to fix Issue #520 -- I have not gotten all fixtures to work correctly, so integration tests fail. But with manual testing I was able to consume and produce back and forth from a windows host and a mac osx host.
=> Updates to support Windows

kafka/coordinator/consumer.py, test/test_coordinator.py
=> Improve auto commit task handling with no consumer group

kafka/conn.py, kafka/future.py, test/test_conn.py
=> Handle partial socket send()

kafka/consumer/fetcher.py, kafka/producer/sender.py, kafka/protocol/fetch.py, kafka/protocol/legacy.py, kafka/protocol/produce.py
=> KAFKA-2136: support Fetch and Produce v1 (throttle_time_ms)

kafka/client.py, kafka/client_async.py, kafka/conn.py, test/conftest.py, test/test_client_async.py, test/test_conn.py, test/test_consumer_group.py, test/test_coordinator.py
This PR extracts general connection logic improvements from the SSL feature branch.
=> Simplify connection logic

kafka/client_async.py, kafka/selectors34.py, test/test_client_async.py
=> Manage non-blocking I/O events with selectors module

kafka/coordinator/base.py, kafka/coordinator/consumer.py
=> Avoid Coordinator `__del__` exceptions

kafka/metrics/stats/sensor.py
pulling in this small bug fix from https://github.com/apache/kafka/pull/1265/files#diff-8736b7fd8ad077ea55ea2a8ad61285faR99
=> small bug fix in Sensor

kafka/producer/record_accumulator.py
=> KAFKA-3388: Fix expiration of batches sitting in the accumulator

kafka/conn.py
Logging to help investigate decoding errors like #713
=> Catch response decode errors and log details

kafka/protocol/message.py, test/test_protocol.py
Fix for #713 -- regression in partial messageset handling.
=> Fix regression in MessageSet decoding wrt PartialMessages

kafka/errors.py
tweak spelling mistake of PARTITON to PARTITION
=> tweak spelling mistake

kafka/client_async.py
This PR makes the least_loaded_node implementation consistent with the official java implementation. And it should fix a bug which could cause least_loaded_node to always return the same unavailable node.
=> least_loaded_node() improvements

kafka/client_async.py, kafka/conn.py
=> check_version should scan nodes until version found or timeout

kafka/conn.py
assert will be disabled by "python -O", it's hard to debug.
=> assert will be disabled by "python -O"

kafka/coordinator/base.py, kafka/coordinator/consumer.py, test/test_coordinator.py
=> Fix KafkaConsumer autocommit for 0.8 brokers

kafka/client.py, kafka/client_async.py, kafka/cluster.py, kafka/protocol/metadata.py, kafka/protocol/types.py, kafka/structs.py, test/test_client.py, test/test_client_async.py
=> Use Metadata Request/Response v1 with 0.10+ brokers

kafka/client_async.py
=> Protect writes to wakeup socket with threading lock

kafka/future.py, kafka/producer/future.py
=> Simplify RecordMetadata; short circuit callbacks

kafka/consumer/fetcher.py, kafka/producer/buffer.py, kafka/producer/future.py, kafka/producer/kafka.py, kafka/producer/record_accumulator.py
=> KAFKA-3196: Add checksum and size to RecordMetadata and ConsumerRecord

kafka/client_async.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/coordinator/heartbeat.py, kafka/producer/kafka.py, kafka/producer/sender.py
client, base coordinator, and a few extra producer metrics.
=> More metrics

kafka/client_async.py
=> Ignore socket.error when checking for protocol out of sync

kafka/client_async.py, kafka/conn.py, kafka/consumer/fetcher.py, kafka/consumer/group.py, kafka/coordinator/base.py, kafka/coordinator/consumer.py, kafka/producer/buffer.py, kafka/producer/kafka.py, kafka/producer/record_accumulator.py, kafka/producer/sender.py, test/test_client_async.py, test/test_coordinator.py, test/test_fetcher.py
This PR completes metrics instrumentation by adding connection-level stats, both per-node and aggregates.
=> Complete metrics instrumentation

kafka/conn.py
=> HOTFIX: Fix BrokerConnectionMetrics when sensors already exist

.travis.yml, build_integration.sh, docs/tests.rst, servers/0.10.0.1/resources/kafka.properties, servers/0.10.0.1/resources/log4j.properties, servers/0.10.0.1/resources/zookeeper.properties
This PR adds 0.10.0.1 to integration tests in place of 0.10.0.0
=> Use 0.10.0.1 for integration tests

kafka/conn.py
=> Fix check_version on 0.9 brokers w/ max_in_flight_requests_per_connection = 1

kafka/consumer/fetcher.py, kafka/consumer/group.py
Smoke testing suggests that max_poll_records=1 is not performant for consumers with a large number of partition assignments. This pull request brings back the internal generators that previously powered consumer iteration. If/when max_poll_records=1 tuning improves we can consider reverting.
=> Dont use max_poll_records=1 for consumer iterators

kafka/errors.py
=> Args are optional in BrokerResponseError str

kafka/consumer/group.py
=> Add docstring for max_records

kafka/__init__.py, kafka/consumer/fetcher.py, kafka/producer/kafka.py, kafka/serializer/__init__.py, kafka/serializer/abstract.py
=> Add kafka.serializer interfaces

kafka/conn.py
=> Fix typo: coorelation --> correlation

test/conftest.py, test/test_metrics.py
http://doc.pytest.org/en/latest/fixture.html#fixture-finalization-executing-teardown-code
=> Update pytest fixtures to new yield syntax

kafka/consumer/base.py, kafka/consumer/group.py, test/test_client_async.py, test/testutil.py
=> Spelling and grammar changes

kafka/protocol/admin.py
New in 0.10.1.0 per KIP-4 / KAFKA-2945 / KAFKA-2946
Fix #857
=> Add CreateTopics / DeleteTopics Structs

kafka/protocol/fetch.py
Adds the structs required for #870 - still some todo's left before that issue can be closed.
=> Add FetchRequest/Response_v3 structs

kafka/protocol/offset.py
Those can be used to request the offset of a stream at a given timepoint
=> Add support for offsetRequestV1 messages

kafka/conn.py
I wrapped ssl module importing and add the recovery path from ImportError.
* Unlike my initial assumption, I understood that ssl library is depended by many standard library modules (e.g hashlib), so this workaround may not be effective on practice. :( 
* Such workaround is implemented many third-party modules (e.g redis-py), so regardless of the effectiveness I think this workaround is necessarily to retain the library's versatility.
=> Add support for Python built without ssl (#939)

kafka/protocol/group.py
The JoinGroupRequest struct added a rebalance_timeout as part of KIP-62 / KAFKA-3888
=> Add JoinGroup v1 structs

kafka/protocol/metadata.py
https://cwiki.apache.org/confluence/display/KAFKA/KIP-78:+Cluster+Id
=> Add MetadataRequest_v2 and MetadataResponse_v2 structures for KIP-78

kafka/client_async.py, kafka/conn.py, kafka/consumer/group.py, kafka/producer/kafka.py
=> Fix SimpleClient Broker API version default

kafka/producer/buffer.py
=> Issue 985: Clear memory wait condition before raising Exception

kafka/conn.py
=> Fix sasl reconnect bug: auth future must be reset on close

kafka/errors.py
see https://kafka.apache.org/protocol#protocol_error_codes
=> More errors -- sync with upstream broker exception list

kafka/protocol/admin.py
Adding protocol structs for KIP-108
=> CreateTopicsRequest / Response v1

kafka/consumer/group.py
Oops, didn't mean to have such an undescriptive commit message. Got confused by GitHub's web UI... I don't think it's worth the time to fix, but I can if you really want.
=> A few Sphinx updates

kafka/client_async.py
This should not change existing behavior. Intent here is simply to support using ready without the metadata-priority check. This may be useful with group coordinator logic.
=> Add optional kwarg to disable metadata-priority logic

kafka/protocol/struct.py, test/test_protocol.py
=> Fix kwarg handing in kafka.protocol.struct.Struct

kafka/consumer/group.py, test/test_consumer.py
=> Return copy of consumer subscription set

kafka/consumer/group.py, kafka/coordinator/consumer.py
=> Optionally skip auto-commit during consumer.close

pylint.rc
See https://github.com/PyCQA/pylint/issues/782
=> Ignore not-context-manager pylint error

kafka/client_async.py
This should fix #1164 and #1166
=> Select on sockets to avoid busy polling during bootstrap

.travis.yml, build_integration.sh
Also switches to scala 2.11 artifacts. Removing 0.10.1.1 to keep total test time down.
=> Add 0.11.0.0 to travis test matrix, remove 0.10.1.1

kafka/consumer/fetcher.py, test/test_fetcher.py
=> Fix message handling when fetching offset mid-compressed-batch

setup.cfg
https://wheel.readthedocs.io/en/stable/index.html#including-the-license-in-the-generated-wheel-file
=> Add license to wheel

.travis.yml
=> Add kafka 1.0.0 to travis integration tests

requirements-dev.txt, tox.ini
I believe #1328 was fixed upstream
=> pylint 1.8.2

kafka/client_async.py
=> Fix pending completion IndexError bug caused by multiple threads

kafka/coordinator/base.py
see https://issues.apache.org/jira/browse/KAFKA-5512
=> KAFKA-5512 -- awake the heartbeat thread when it is time to poll

kafka/client_async.py, kafka/consumer/group.py, kafka/producer/kafka.py
This was added in #1068 but never documented.
Fix #1497
=> Document connections_max_idle_ms

kafka/client_async.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1636)
=> Use TypeError for invalid type

docs/apidoc/KafkaAdmin.rst, docs/apidoc/modules.rst, kafka/__init__.py, kafka/admin/__init__.py, kafka/admin/kafka.py
Fix #1621 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1652)
=> Rename KafkaAdmin to KafkaAdminClient

test/test_admin.py
Cleanup the formatting, remove parens, extraneous spaces, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1653)
=> Cleanup formatting, no functional changes

kafka/admin/client.py, kafka/protocol/admin.py
Fix #1657
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1658)
=> Fix response error checking in KafkaAdminClient send_to_controller

kafka/conn.py
Fixes #1686 -- SSL connections should timeout if not fully connected within the request_timeout_ms configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1696)
=> Timeout all unconnected conns (incl SSL) after request_timeout_ms

kafka/producer/record_accumulator.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1705)
=> Remove unused import

kafka/conn.py, kafka/consumer/subscription_state.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1865)
=> Fix minor typo

kafka/client_async.py
i.e: https://github.com/dpkp/kafka-python/blob/1.4.7/kafka/conn.py#L135.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1921)
=> Update docstring to match conn.py's

kafka/coordinator/base.py
Closes #1965
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1966)
=> Fix simple typo: managementment -> management

kafka/coordinator/base.py
Fixes #1943
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1975)
=> Change retriable coordinator failures log-level to debug

.travis.yml, README.rst, docs/compatibility.rst, docs/index.rst, servers/2.4.0/resources/kafka.properties, servers/2.4.0/resources/log4j.properties, servers/2.4.0/resources/zookeeper.properties
adds [kafka 2.4.0](https://www.apache.org/dist/kafka/2.4.0/RELEASE_NOTES.html) to the CI tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1972)
=> kafka 2.4.0

benchmarks/load_example.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/1983)
=> Use print() function in both Python 2 and Python 3

README.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2045)
=> fixed the broken compatibility page link

setup.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2069)
=> Added crc32c extra requirement as per issue #2068

kafka/producer/kafka.py
Documentation link fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2226)
=> Fix producerconfigs documentation link

tox.ini
Could make experimental tests easier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2382)
=> Add py312 to tox.ini

test/fixtures.py
Mitigates concern raised in https://nvd.nist.gov/vuln/detail/CVE-2018-1281.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2384)
=> Update fixtures.py to use "127.0.0.1" for local ports

kafka/conn.py
Closes #2399.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dpkp/kafka-python/2407)
=> Update conn.py to catch OSError in case of failed import on Windows

setup.cfg
=> Update license_file to license_files

kafka/protocol/admin.py
=> Fix DescribeConfigsResponse_v1 config_source

README.rst, docs/index.rst
=> Update some RST documentation syntax

kafka/protocol/admin.py
=> Fix base class of DescribeClientQuotasResponse_v0

.github/workflows/python-package.yml
=> Test with jvm 23

kafka/conn.py
=> Strip trailing dot off hostname.

kafka/conn.py
=> Log connection errors at ERROR level

kafka/coordinator/base.py
=> Avoid self-join in heartbeat thread close

kafka/admin/client.py, kafka/protocol/admin.py, test/conftest.py, test/test_admin_integration.py
=> AdminClient: support delete_records

kafka/producer/kafka.py
=> Raise immediate error on producer.send after close

kafka/consumer/fetcher.py
=> Fix Fetcher retriable error handling

kafka/client_async.py
=> Also update config api_version to closest compatible

kafka/client_async.py, kafka/protocol/metadata.py, test/test_client_async.py
=> Fix MetadataRequest for no topics

kafka/conn.py
=> Always try ApiVersionsRequest v0, even on broker disconnect

kafka/consumer/fetcher.py, test/test_fetcher.py
=> Fix Fetch._reset_offsets_async() KeyError when fetching from multiple nodes
